<?php
    include($_SERVER['DOCUMENT_ROOT'].'/sweeteaze/controllers/title.inc.php');
    require_once('controllers/config.inc.php');
    $currentPage = basename($_SERVER['SCRIPT_FILENAME']);

    ?>
<!DOCTYPE html>
<html>
<head>
    <!-- ==========================
    	Meta Tags 
    =========================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
 
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,900,800' rel='stylesheet' type='text/css'>

    <?php include('controllers/html_dependencies_top.inc.php'); ?>
    
</head>
<body>
	
    <!-- ==========================
    	SCROLL TOP - START 
    =========================== -->
    <div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
    <!-- ==========================
    	SCROLL TOP - END 
    =========================== -->
    

    
    <div id="page-wrapper"> <!-- PAGE - START -->
    
	<!-- ==========================
    	HEADER - START 
    =========================== -->
    <?php include('controllers/header.inc.php'); ?>
    <!-- ==========================
    	HEADER - END 
    =========================== -->
    
    <!-- ==========================
    	BREADCRUMB - START 
    =========================== -->
    <section class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <h2></h2>
                    <p></p>
                </div>
                <div class="col-xs-6">
                    <ol class="breadcrumb">
                        <li><a href="index.phtml">Home</a></li>
                        <li class="active">About Us</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
	<!-- ==========================
    	BREADCRUMB - END 
    =========================== -->
    
    <!-- ==========================
    	ESHOP - START 
    =========================== -->
    <section class="content eshop">
        <div class="container">
        	<div class="default-style about">
        		<h2>About Us</h2>
               	<div class="row">
                	<div class="col-sm-7 col-md-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.</p>
                        <p>Sed eget pulvinar quam, vel feugiat enim. Aliquam erat volutpat. Phasellus eu porta ipsum. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per. Vestibulum velmo.</p>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check"></i>Etiam sed dolor ac diam volutpat</li>
                            <li><i class="fa fa-check"></i>Erat volutpat. Phasellus eu porta ipsum suspendisse aliquet imperdiet</li>
                            <li><i class="fa fa-check"></i>Phasellus eu porta ipsum. Suspendisse aliquet imperdiet commodo</li>
                            <li><i class="fa fa-check"></i>Sed eget pulvinar quam, vel feugiat enim aliquam</li>
                        </ul>
                    </div>
                    <div class="col-sm-5 col-md-6">
                    	<img src="assets/images/slide-3.jpg" class="img-responsive" alt="">
                    </div>
                </div>
                <div class="icon-nav row">
                    <!--<div class="col-xs-6 col-sm-3"><a href="stores.html"><i class="fa fa-map-marker"></i> Our Stores</a></div>-->
                    <div class="col-xs-6 col-sm-3"><a href="privacy-policy.phtml"><i class="fa fa-lock"></i> Privacy Policy</a></div>
                    <div class="col-xs-6 col-sm-3"><a href="terms-conditions.phtml"><i class="fa fa-book"></i> Terms & Conditions</a></div>
                    <div class="col-xs-6 col-sm-3"><a href="faq.phtml"><i class="fa fa-question-circle"></i> FAQ</a></div>
                </div>
                
                <div class="services">
                    <h2 class="text-center">Our Services</h2>
                    <div class="row row-no-padding">
                
                        <!-- SERVICE - START -->
                        <div class="col-xs-6 col-sm-4">
                            <div class="service">
                                <i class="fa fa-star"></i>
                                <h3>FREE SHIPPING ON ALL ORDRES</h3>
                                <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                            </div>
                        </div>
                        <!-- SERVICE - END -->
                        
                        <!-- SERVICE - START -->
                        <div class="col-xs-6 col-sm-4">
                            <div class="service">
                                <i class="fa fa-heart"></i>
                                <h3>AMAZING CUSTOMER SERVICE</h3>
                                <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                            </div>
                        </div>
                        <!-- SERVICE - END -->
                        
                        <!-- SERVICE - START -->
                        <div class="col-xs-6 col-sm-4">
                            <div class="service">
                                <i class="fa fa-rocket"></i>
                                <h3>NO CUSTOMS OR DUTY FEES!</h3>
                                <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                            </div>
                        </div>
                        <!-- SERVICE - END -->
                
                        <!-- SERVICE - START -->
                        <div class="col-xs-6 col-sm-4">
                            <div class="service">
                                <i class="fa fa-star"></i>
                                <h3>FREE SHIPPING ON ALL ORDRES</h3>
                                <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                            </div>
                        </div>
                        <!-- SERVICE - END -->
                        
                        <!-- SERVICE - START -->
                        <div class="col-xs-6 col-sm-4">
                            <div class="service">
                                <i class="fa fa-heart"></i>
                                <h3>AMAZING CUSTOMER SERVICE</h3>
                                <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                            </div>
                        </div>
                        <!-- SERVICE - END -->
                        
                        <!-- SERVICE - START -->
                        <div class="col-xs-6 col-sm-4">
                            <div class="service">
                                <i class="fa fa-rocket"></i>
                                <h3>NO CUSTOMS OR DUTY FEES!</h3>
                                <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                            </div>
                        </div>
                        <!-- SERVICE - END -->
                        
                    </div>
                    
                </div>
                
        	</div>
        </div>
    </section>
    <!-- ==========================
    	ESHOP - END 
    =========================== -->
       
    <!-- ==========================
    	NEWSLETTER - START 
    =========================== -->
    <?php include('controllers/newsletter.inc.php'); ?>
    <!-- ==========================
    	NEWSLETTER - END 
    =========================== -->
    
    <!-- ==========================
    	FOOTER - START 
    =========================== -->
    <?php include('controllers/footer.inc.php'); ?>
    <!-- ==========================
    	FOOTER - END 
    =========================== -->
    

    
    </div> <!-- PAGE - END -->
    
   	<!-- ==========================
    	JS 
    =========================== -->        
	<?php include('controllers/html_dependencies_bottom.inc.php'); ?>
</body>
</html>