<!DOCTYPE html>
<html>
<head>
    <!-- ==========================
    	Meta Tags 
    =========================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- ==========================
    	Title 
    =========================== -->
    <title>uMarket - The easiest way to shop</title>
        
    <!-- ==========================
    	Fonts 
    =========================== -->
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,900,800' rel='stylesheet' type='text/css'>

    <!-- ==========================
    	CSS 
    =========================== -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="http://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="assets/css/dragtable.css" rel="stylesheet" type="text/css">
    <link href="assets/css/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="assets/css/animate.css" rel="stylesheet" type="text/css">
    <link href="assets/css/color-switcher.css" rel="stylesheet" type="text/css">
    <link href="assets/css/custom.css" rel="stylesheet" type="text/css">
    <link href="assets/css/color/red.css" id="main-color" rel="stylesheet" type="text/css">
    
    <!-- ==========================
    	JS 
    =========================== -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>
	
    <!-- ==========================
    	SCROLL TOP - START 
    =========================== -->
    <div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
    <!-- ==========================
    	SCROLL TOP - END 
    =========================== -->
    
	<!-- ==========================
    	COLOR SWITCHER - START 
    =========================== -->
	<div id="color-switcher">
        <div id="toggle-switcher"><i class="fa fa-gear"></i></div>
        <span>Color Scheme:</span>
        <ul class="list-unstyled list-inline">
            <li id="red" data-toggle="tooltip" data-placement="top" title="" data-original-title="Red"></li>
            <li id="purple" data-toggle="tooltip" data-placement="top" title="" data-original-title="Purple"></li>
            <li id="yellow" data-toggle="tooltip" data-placement="top" title="" data-original-title="Yellow"></li>
            <li id="blue" data-toggle="tooltip" data-placement="top" title="" data-original-title="Blue"></li>
            <li id="dark-blue" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dark Blue"></li>
            <li id="orange" data-toggle="tooltip" data-placement="top" title="" data-original-title="Orange"></li>
            <li id="green" data-toggle="tooltip" data-placement="top" title="" data-original-title="Green"></li>
            <li id="brown" data-toggle="tooltip" data-placement="top" title="" data-original-title="Brown"></li>
            <li id="dark-red" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dark Red"></li>
            <li id="light-green" data-toggle="tooltip" data-placement="top" title="" data-original-title="Light Green"></li>
        </ul>
    </div>
	<!-- ==========================
    	COLOR SWITCHER - END 
    =========================== -->
    
    <div id="page-wrapper"> <!-- PAGE - START -->
    
	<!-- ==========================
    	HEADER - START 
    =========================== -->
	<div class="top-header hidden-xs">
    	<div class="container">
            <div class="row">
                <div class="col-sm-5">
                    <ul class="list-inline contacts">
                        <li><i class="fa fa-envelope"></i> help@umarket.com</li>
                        <li><i class="fa fa-phone"></i> 754 213 456</li>
                    </ul>
                </div>
                <div class="col-sm-7 text-right">
                    <ul class="list-inline links">
                        <li><a href="my-account.html">My account</a></li>
                        <li><a href="checkout.html">Checkout</a></li>
                        <li><a href="wishlist.html">Wishlist (5)</a></li>
                        <li><a href="compare.html">Compare (3)</a></li>
                        <li><a href="signin.html">Logout</a></li>
                    </ul>
                    <ul class="list-inline languages hidden-sm">
                    	<li><a href="#"><img src="assets/images/flags/cz.png" alt="cs_CZ"></a></li>
                        <li><a href="#"><img src="assets/images/flags/us.png" alt="en_US"></a></li>
                        <li><a href="#"><img src="assets/images/flags/de.png" alt="de_DE"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <header class="navbar navbar-default navbar-static-top">
    	<div class="container">
            <div class="navbar-header">
                <a href="index.html" class="navbar-brand"><span>u</span>Market</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></button>
            </div>
            <div class="navbar-collapse collapse">
            	<p class="navbar-text hidden-xs hidden-sm">The easiest way to shop</p>
            	<ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Home</a>
                      	<ul class="dropdown-menu">
                        	<li><a href="index.html">Homepage 1</a></li>
                            <li><a href="homepage-2.html">Homepage 2</a></li>
                            <li><a href="homepage-3.html">Homepage 3<span class="label label-warning pull-right">Updated</span></a></li>
                            <li><a href="homepage-4.html">Homepage 4</a></li>
                            <li><a href="homepage-5.html">Homepage 5<span class="label label-danger pull-right">New</span></a></li>
                            <li><a href="homepage-6.html">Homepage 6<span class="label label-danger pull-right">New</span></a></li>
                      	</ul>
                    </li>
                    <li class="dropdown megamenu">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Eshop</a>
                      	<ul class="dropdown-menu">
                            <li class="col-sm-4 col-md-3">
                            	<ul class="list-unstyled">
                                	<li class="title">Men <span class="label label-danger pull-right">HOT</span></li>
                                    <li><a href="products.html">Sweatshirts & Jackets</a></li>
                                    <li><a href="products.html">Caps and Hats</a></li>
                                    <li><a href="products.html">Ties</a></li>
                                    <li><a href="products.html">Scarves</a></li>
                                    <li><a href="products.html">Shirts</a></li>
                                    <li><a href="products.html">Jeans</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4 col-md-3">
                            	<ul class="list-unstyled">
                                	<li class="title">Women <span class="label label-info pull-right">30% OFF SALE</span></li>
                                    <li><a href="products.html">Jackets & Coats</a></li>
                                    <li><a href="products.html">Jumpers & cardigans</a></li>
                                    <li><a href="products.html">Jeans</a></li>
                                    <li><a href="products.html">Trousers</a></li>
                                    <li><a href="products.html">Dresses</a></li>
                                    <li><a href="products.html">Long Sleeve Tops</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4 col-md-3">
                            	<ul class="list-unstyled">
                                	<li class="title">Accessories</li>
                                    <li><a href="products.html">Sunglasses</a></li>
                                    <li><a href="products.html">Watches</a></li>
                                    <li><a href="products.html">Umbrellas</a></li>
                                    <li><a href="products.html">Bags & Wallets</a></li>
                                    <li><a href="products.html">Fashion Jewellery</a></li>
                                    <li><a href="products.html">Belts</a></li>
                                </ul>
                            </li>
                            <li class="hidden-xs hidden-sm col-md-3">
                            	<img src="assets/images/megamenu.png" class="img-responsive center-block" alt="">
                            </li>
                      	</ul>
                    </li>
                    <li class="dropdown megamenu">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Pages</a>
                      	<ul class="dropdown-menu">
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                	<li class="title">Eshop</li>
                                    <li><a href="products.html">Products</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="compare.html">Compare</a></li>
                                    <li><a href="single-product.html">One Product</a></li>
                                    <li><a href="stores.html">Stores</a></li>
                                    <li><a href="about-shop.html">About Shop</a></li>
                                    <li><a href="lookbook.html">Lookbook</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                	<li class="title">Account</li>
                                    <li><a href="my-account.html">My Account<span class="label label-warning pull-right">Updated</span></a></li>
                                    <li><a href="profile.html">Profile</a></li>
                                    <li><a href="orders.html">Ordres</a></li>
                                    <li><a href="wishlist.html">Wishlist</a></li>
                                    <li><a href="address.html">Address</a></li>
                                    <li><a href="warranty-claims.html">Warranty Claims<span class="label label-danger pull-right">New</span></a></li>
                                    <li><a href="signup.html">Sign Up</a></li>
                                    <li><a href="signin.html">Sign In</a></li>
                                    <li><a href="lost-password.html">Lost Password</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                	<li class="title">Other Pages</li>
                                    <li><a href="blog.html">Blog</a></li>
                                    <li><a href="single-post.html">One Blog Post</a></li>
                                    <li><a href="single-order.html">Order Detail</a></li>
                                    <li><a href="downloads.html">Downloads<span class="label label-danger pull-right">New</span></a></li>
                                    <li><a href="faq.html">FAQ</a></li>
                                    <li><a href="privacy-policy.html">Privacy Policy</a></li>
                                    <li><a href="terms-conditions.html">Terms & Conditions</a></li>
                                    <li><a href="404.html">404 Error</a></li>
                                    <li><a href="email-template.html" target="_blank">Email Template</a></li>
                                </ul>
                            </li>
                      	</ul>
                    </li>
                    <li class="dropdown megamenu">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Components<span class="label label-danger pull-right">New</span></a>
                      	<ul class="dropdown-menu">
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                    <li><a href="components.html#headings">Headings</a></li>
                                    <li><a href="components.html#paragraphs">Paragraphs</a></li>
                                    <li><a href="components.html#lists">Lists</a></li>
                                    <li><a href="components.html#tabs">Tabs</a></li>
                                    <li><a href="components.html#accordition">Accordition</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                    <li><a href="components.html#collapse">Collapse</a></li>
                                    <li><a href="components.html#buttons">Buttons</a></li>
                                    <li><a href="components.html#tables">Tables</a></li>
                                    <li><a href="components.html#grids">Grids</a></li>
                                    <li><a href="components.html#responsive-video-audio">Responsive Video &amp; Audio</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                    <li><a href="components.html#alerts">Alerts</a></li>
                                    <li><a href="components.html#forms">Forms</a></li>
                                    <li><a href="components.html#labels">Labels</a></li>
                                    <li><a href="components.html#paginations">Paginations</a></li>
                                    <li><a href="components.html#carousels">Carousels</a></li>
                                </ul>
                            </li>
                      	</ul>
                    </li>
                    <li class="dropdown navbar-cart hidden-xs">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true"><i class="fa fa-shopping-cart"></i></a>
                      	<ul class="dropdown-menu">
                        	
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-3">
                                    	<img src="assets/images/products/product-1.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-9">
                                    	<h4><a href="single-product.html">Fusce Aliquam</a></h4>
                                        <p>1x - $20.00</p>
                                    	<a href="#" class="remove"><i class="fa fa-times-circle"></i></a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-3">
                                    	<img src="assets/images/products/product-2.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-9">
                                    	<h4><a href="single-product.html">Fusce Aliquam</a></h4>
                                        <p>1x - $20.00</p>
                                    	<a href="#" class="remove"><i class="fa fa-times-circle"></i></a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-3">
                                    	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-9">
                                    	<h4><a href="single-product.html">Fusce Aliquam</a></h4>
                                        <p>1x - $20.00</p>
                                    	<a href="#" class="remove"><i class="fa fa-times-circle"></i></a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-6">
                                    	<a href="cart.html" class="btn btn-primary btn-block">View Cart</a>
                                    </div>
                                    <div class="col-sm-6">
                                    	<a href="checkout.html" class="btn btn-primary btn-block">Checkout</a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                      	</ul>
                    </li>
                    <li class="dropdown navbar-search hidden-xs">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
                      	<ul class="dropdown-menu">
                        	<li>
                                <form>
                                    <div class="input-group input-group-lg">
                                        <input type="text" class="form-control" placeholder="Search ...">
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary" type="button">Search</button>
                                        </span>
                                    </div>
                                </form>
                            </li>
                      	</ul>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <!-- ==========================
    	HEADER - END 
    =========================== -->
        
    <!-- ==========================
    	BREADCRUMB - START 
    =========================== -->
    <section class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <h2>Blog</h2>
                    <p>All Categories</p>
                </div>
                <div class="col-xs-6">
                    <ol class="breadcrumb">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="blog.html">Blog</a></li>
                        <li class="active">All Categories</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
	<!-- ==========================
    	BREADCRUMB - END 
    =========================== -->
    
    <!-- ==========================
    	BLOG - START 
    =========================== -->
    <section class="content blog">
        <div class="container">
            <h2 class="hidden">Blog</h2>
            <div class="row">
            	<div class="col-sm-9">
                	
                    <!-- POST - START -->
                    <article class="post">
                    	<div class="post-left">
                        	<div class="author">
                            	<img src="assets/images/avatar/avatar_01.jpg" class="img-responsive img-circle" alt="">
                                <span>Posted by</span>
                                <span class="name">John Doe</span>
                            </div>
                        </div>
                    	<h3><a href="single-post.html">Pyjamas for a good night</a></h3>
                        <div class="meta">
                            <div class="date">20/12/2015</div>
                            <div class="date visible-xs-inline-block">John Doe</div>
                            <div class="category">Uncategorized</div>
                        </div>
                        <div class="attachment">
                        	<img src="assets/images/blog/blog-4.jpg" class="img-responsive" alt="">
                        </div>
                        <p>Nam vehicula vestibulum leo sit amet tristique. Cras laoreet elit non enim sodales, sit amet dictum felis lobortis. Nam ut elementum nibh, eget bibendum risus. Maecenas a metus non eros vestibulum bibendum sit amet vel dui. Phasellus convallis elit diam, ut porttitor magna pellentesque id. Pellentesque sed orci dolor. Aliquam aliquet dolor eget diam varius</p>
                    	<p>Morbi non aliquet felis. Nullam lectus risus, pretium eu rhoncus quis, ultrices et dolor. Cras eget sem vitae velit cursus pulvinar in a urna arcu nisi, pellentesque nec gravida quis, fringilla eget mi. In malesuada placerat diam at posuere lorem concordia.</p>
                        <div class="post-bottom clearfix">
                            <div class="tags">
                                <span class="label"><i class="fa fa-tag"></i><a href="#">book</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">music</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">nature</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">read</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">songs</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">sunshine</a></span>
                            </div>
                            <a href="single-post.html" class="btn btn-primary">Read More</a>
                        </div>
                    </article>
                    <!-- POST - END -->
                    
                    <!-- POST - START -->
                    <article class="post">
                    	<div class="post-left">
                        	<div class="author">
                            	<img src="assets/images/avatar/avatar_01.jpg" class="img-responsive img-circle" alt="">
                                <span>Posted by</span>
                                <span class="name">John Doe</span>
                            </div>
                        </div>
                    	<h3><a href="single-post.html">Professional Habits To Adopt</a></h3>
                        <div class="meta">
                            <div class="date">01/12/2015</div>
                            <div class="date visible-xs-inline-block">John Doe</div>
                            <div class="category">Uncategorized</div>
                        </div>
                        <div class="attachment">
                        	<div class="embed-responsive embed-responsive-16by9">
                            	<iframe src="https://player.vimeo.com/video/120197450"></iframe>
                            </div>
                        </div>
                        <p>Nam vehicula vestibulum leo sit amet tristique. Cras laoreet elit non enim sodales, sit amet dictum felis lobortis. Nam ut elementum nibh, eget bibendum risus. Maecenas a metus non eros vestibulum bibendum sit amet vel dui. Phasellus convallis elit diam, ut porttitor magna pellentesque id. Pellentesque sed orci dolor. Aliquam aliquet dolor eget diam varius</p>
                    	<p>Morbi non aliquet felis. Nullam lectus risus, pretium eu rhoncus quis, ultrices et dolor. Cras eget sem vitae velit cursus pulvinar in a urna arcu nisi, pellentesque nec gravida quis, fringilla eget mi. In malesuada placerat diam at posuere lorem concordia.</p>
                        <div class="post-bottom clearfix">
                            <div class="tags">
                                <span class="label"><i class="fa fa-tag"></i><a href="#">book</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">music</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">nature</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">read</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">songs</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">sunshine</a></span>
                            </div>
                            <a href="single-post.html" class="btn btn-primary">Read More</a>
                        </div>
                    </article>
                    <!-- POST - END -->
                    
                    <!-- POST - START -->
                    <article class="post">
                    	<div class="post-left">
                        	<div class="author">
                            	<img src="assets/images/avatar/avatar_01.jpg" class="img-responsive img-circle" alt="">
                                <span>Posted by</span>
                                <span class="name">John Doe</span>
                            </div>
                        </div>
                    	<h3><a href="single-post.html">How to pickup shoes</a></h3>
                        <div class="meta">
                            <div class="date">24/11/2015</div>
                            <div class="date visible-xs-inline-block">John Doe</div>
                            <div class="category">Uncategorized</div>
                        </div>
                        <div class="attachment">
                        	<div id="blog-post-gallery" class="nav-inside">       
                            	<div class="item"><img src="assets/images/blog/blog-1.jpg" class="img-responsive" alt=""></div>
                                <div class="item"><img src="assets/images/blog/blog-2.jpg" class="img-responsive" alt=""></div>
                                <div class="item"><img src="assets/images/blog/blog-3.jpg" class="img-responsive" alt=""></div>
                                <div class="item"><img src="assets/images/blog/blog-4.jpg" class="img-responsive" alt=""></div>
                            </div>
                        </div>
                        <p>Nam vehicula vestibulum leo sit amet tristique. Cras laoreet elit non enim sodales, sit amet dictum felis lobortis. Nam ut elementum nibh, eget bibendum risus. Maecenas a metus non eros vestibulum bibendum sit amet vel dui. Phasellus convallis elit diam, ut porttitor magna pellentesque id. Pellentesque sed orci dolor. Aliquam aliquet dolor eget diam varius</p>
                    	<p>Morbi non aliquet felis. Nullam lectus risus, pretium eu rhoncus quis, ultrices et dolor. Cras eget sem vitae velit cursus pulvinar in a urna arcu nisi, pellentesque nec gravida quis, fringilla eget mi. In malesuada placerat diam at posuere lorem concordia.</p>
                        <div class="post-bottom clearfix">
                            <div class="tags">
                                <span class="label"><i class="fa fa-tag"></i><a href="#">book</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">music</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">nature</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">read</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">songs</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">sunshine</a></span>
                            </div>
                            <a href="single-post.html" class="btn btn-primary">Read More</a>
                        </div>
                    </article>
                    <!-- POST - END -->
                    
                    <!-- POST - START -->
                    <article class="post">
                    	<div class="post-left">
                        	<div class="author">
                            	<img src="assets/images/avatar/avatar_01.jpg" class="img-responsive img-circle" alt="">
                                <span>Posted by</span>
                                <span class="name">John Doe</span>
                            </div>
                        </div>
                    	<h3><a href="single-post.html">Fine mens gloves</a></h3>
                        <div class="meta">
                            <div class="date">10/11/2015</div>
                            <div class="date visible-xs-inline-block">John Doe</div>
                            <div class="category">Uncategorized</div>
                        </div>
                        <div class="attachment">
                        	<div class="embed-responsive embed-responsive-audio">
                           		<iframe height="166" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/147737117&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
                            </div>
                        </div>
                        <p>Nam vehicula vestibulum leo sit amet tristique. Cras laoreet elit non enim sodales, sit amet dictum felis lobortis. Nam ut elementum nibh, eget bibendum risus. Maecenas a metus non eros vestibulum bibendum sit amet vel dui. Phasellus convallis elit diam, ut porttitor magna pellentesque id. Pellentesque sed orci dolor. Aliquam aliquet dolor eget diam varius</p>
                    	<p>Morbi non aliquet felis. Nullam lectus risus, pretium eu rhoncus quis, ultrices et dolor. Cras eget sem vitae velit cursus pulvinar in a urna arcu nisi, pellentesque nec gravida quis, fringilla eget mi. In malesuada placerat diam at posuere lorem concordia.</p>
                        <div class="post-bottom clearfix">
                            <div class="tags">
                                <span class="label"><i class="fa fa-tag"></i><a href="#">book</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">music</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">nature</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">read</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">songs</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">sunshine</a></span>
                            </div>
                            <a href="single-post.html" class="btn btn-primary">Read More</a>
                        </div>
                    </article>
                    <!-- POST - END -->
                    
                    <!-- POST - START -->
                    <article class="post">
                    	<div class="post-left">
                        	<div class="author">
                            	<img src="assets/images/avatar/avatar_01.jpg" class="img-responsive img-circle" alt="">
                                <span>Posted by</span>
                                <span class="name">John Doe</span>
                            </div>
                        </div>
                    	<h3><a href="single-post.html">Sunglasses for a beach</a></h3>
                        <div class="meta">
                            <div class="date">18/10/2015</div>
                            <div class="date visible-xs-inline-block">John Doe</div>
                            <div class="category">Uncategorized</div>
                        </div>
                        <div class="attachment"></div>
                        <p>Nam vehicula vestibulum leo sit amet tristique. Cras laoreet elit non enim sodales, sit amet dictum felis lobortis. Nam ut elementum nibh, eget bibendum risus. Maecenas a metus non eros vestibulum bibendum sit amet vel dui. Phasellus convallis elit diam, ut porttitor magna pellentesque id. Pellentesque sed orci dolor. Aliquam aliquet dolor eget diam varius</p>
                    	<p>Morbi non aliquet felis. Nullam lectus risus, pretium eu rhoncus quis, ultrices et dolor. Cras eget sem vitae velit cursus pulvinar in a urna arcu nisi, pellentesque nec gravida quis, fringilla eget mi. In malesuada placerat diam at posuere lorem concordia.</p>
                        <div class="post-bottom clearfix">
                            <div class="tags">
                                <span class="label"><i class="fa fa-tag"></i><a href="#">book</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">music</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">nature</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">read</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">songs</a></span>
                                <span class="label"><i class="fa fa-tag"></i><a href="#">sunshine</a></span>
                            </div>
                            <a href="single-post.html" class="btn btn-primary">Read More</a>
                        </div>
                    </article>
                    <!-- POST - END -->
                    
                    <ul class="pagination">
                        <li><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                        <li><a href="#">1</a></li>
                        <li class="active"><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                    </ul>
                    
                </div>
                <div class="col-sm-3">
                	<aside class="sidebar right">
                		
                        <!-- WIDGET:SEARCH - START -->
                        <div class="widget widget-search">
                        	<h3>Search</h3>
                            <div class="widget-body">
                                <form>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
                                        </span>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!-- WIDGET:SEARCH - START -->
                        
                        <!-- WIDGET:POST CATEGORIES - START -->
                        <div class="widget widget-post-categories">
                        	<h3>Categories</h3>
                            <div class="widget-body">
                                <ul class="list-unstyled">
                                    <li><a href="#">Fashion<span class="badge">12</span></a></li>
                                    <li><a href="#">Design<span class="badge">12</span></a></li>
                                    <li><a href="#">Music<span class="badge">12</span></a></li>
                                    <li><a href="#">Travel<span class="badge">12</span></a></li>
                                    <li><a href="#">Uncategorized<span class="badge">12</span></a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- WIDGET:POST CATEGORIES - START -->
                        
                        <!-- WIDGET:TAGS - START -->
                        <div class="widget widget-tags">
                        	<h3>Tags</h3>
                            <div class="widget-body">
                            	<div class="tags">
                                	<span class="label"><i class="fa fa-tag"></i><a href="#">book</a></span>
                                    <span class="label"><i class="fa fa-tag"></i><a href="#">music</a></span>
                                    <span class="label"><i class="fa fa-tag"></i><a href="#">nature</a></span>
                                    <span class="label"><i class="fa fa-tag"></i><a href="#">read</a></span>
                                    <span class="label"><i class="fa fa-tag"></i><a href="#">songs</a></span>
                                    <span class="label"><i class="fa fa-tag"></i><a href="#">sunshine</a></span>
                                </div>
                            </div>
                        </div>
                        <!-- WIDGET:TAGS - START -->
                        
                        <!-- WIDGET:TAGS - START -->
                        <div class="widget widget-recent-comments">
                        	<h3>Recent Comments</h3>
                            <div class="widget-body">
                            	<ul class="list-unstyled">
                                    <li>
                                    	<p class="text"> Nullam lectus risus, pretium eu rhoncus quis</p>
                                        <p>Posted in <a href="single-post.html">Introducing WordPress 4.0 “Benny”</a></p>
                                        <p>By <a href="#">John Doe</a></p>
                                    </li>
                                    <li>
                                    	<p class="text">Nullam lectus risus, pretium eu rhoncus quis, ultrices et dolor. Cras eget sem vitae velit cursus pulvinar in a urna arcu nisi</p>
                                        <p>Posted in <a href="single-post.html">Introducing WordPress 4.0 “Benny”</a></p>
                                        <p>By <a href="#">John Doe</a></p>
                                    </li>
                                    <li>
                                    	<p class="text">Great shoes! Recomended!</p>
                                        <p>Posted in <a href="single-post.html">Introducing WordPress 4.0 “Benny”</a></p>
                                        <p>By <a href="#">John Doe</a></p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- WIDGET:TAGS - START -->
                        
                    </aside>
                </div>
            </div>
        </div>
    </section>
    <!-- ==========================
    	BLOG - END 
    =========================== -->
    
    <!-- ==========================
    	FOOTER - START 
    =========================== -->
    <footer class="navbar navbar-default">
    	<div class="container">
        	<div class="row">
                <div class="col-sm-3 col-xs-6">
                	<div class="footer-widget footer-widget-contacts">
                    	<h4>Contacts</h4>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-envelope"></i> help@umarket.com</li>
                            <li><i class="fa fa-phone"></i> 754 213 456</li>
                            <li><i class="fa fa-map-marker"></i> 40°44'00.9"N 73°59'43.4"W</li>
                            <li class="social">
                            	<a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-tumblr"></i></a>
                            </li>
                        </ul>
                	</div>
                </div>
                <div class="col-sm-3 col-xs-6">
                	<div class="footer-widget footer-widget-links">
                    	<h4>Information</h4>
                        <ul class="list-unstyled">
                        	<li><a href="about-shop.html">About Shop</a></li>
                            <li><a href="stores.html">Our Stores</a></li>
                            <li><a href="terms-conditions.html">Terms & Conditions</a></li>
                            <li><a href="privacy-policy.html">Privacy Policy</a></li>
                            <li><a href="faq.html">FAQ</a></li>
                            <li><a href="my-account.html">My account</a></li>
                        </ul>
                	</div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="footer-widget footer-widget-twitter">
                    	<h4>Recent tweets</h4>
                        <div id="twitter-wrapper"></div>
                	</div>
                </div>
                <div class="col-sm-3 col-xs-6">
                	<div class="footer-widget footer-widget-facebook">
                    	<h4>Facebook Page</h4>
                        <ul class="list-unstyled row row-no-padding">
                        	<li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_01.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_02.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_03.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_04.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_01.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_02.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_03.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_04.jpg" class="img-responsive" alt=""></a></li>
                        </ul>
                        <p>45,500 Likes  <a href="#" class="btn btn-default btn-sm"><i class="fa fa-thumbs-up"></i>Like</a></p>
                	</div>
                </div>
            </div>
            <div class="footer-bottom">
            	<div class="row">
                    <div class="col-sm-6">
                        <p class="copyright">© Umarket 2016 All right reserved.</p>
                        <p class="copyright">Designed by <a href="http://www.pixelized.cz/" target="_blank">Pixelized Studio.</a></p>
                    </div>
                    <div class="col-sm-6">
                        <ul class="list-inline payment-methods">
                        	<li><i class="fa fa-cc-amex"></i></li>
                            <li><i class="fa fa-cc-diners-club"></i></li>
                            <li><i class="fa fa-cc-discover"></i></li>
                            <li><i class="fa fa-cc-jcb"></i></li>
                            <li><i class="fa fa-cc-mastercard"></i></li>
                            <li><i class="fa fa-cc-paypal"></i></li>
                            <li><i class="fa fa-cc-stripe"></i></li>
                            <li><i class="fa fa-cc-visa"></i></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ==========================
    	FOOTER - END 
    =========================== -->
    
    <!-- ==========================
    	MODAL ADVERTISING  - START 
    =========================== -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modalAdvertising">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                    	<div class="col-sm-8">
                        	<h3>Dicount 10%</h3>
                        	<p>Enter your email address and get 10% discount for your first purchase.</p>
                            <form>
                                <div class="input-group">
                                    <input type="email" class="form-control" placeholder="Email Address">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="button">Submit</button>
                                    </span>
                                </div>
                            </form>
                            <div class="checkbox">  
                                <input id="modal-hide" type="checkbox" value="hidden">  
                                <label for="modal-hide">Don't show this popup again</label>
                            </div>
                        </div>
                        <div class="col-sm-4 hidden-xs">
                        	<img src="assets/images/lookbook-1.png" class="img-responsive" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<!-- ==========================
    	MODAL ADVERTISING - END 
    =========================== -->
    
    </div> <!-- PAGE - END -->
    
   	<!-- ==========================
    	JS 
    =========================== -->        
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=true"></script>
	<script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/bootstrap-hover-dropdown.min.js"></script>
    <script src="assets/js/SmoothScroll.js"></script>
    <script src="assets/js/jquery.dragtable.js"></script>
    <script src="assets/js/jquery.card.js"></script>
    <script src="assets/js/owl.carousel.min.js"></script>
    <script src="assets/js/twitterFetcher_min.js"></script>
    <script src="assets/js/jquery.mb.YTPlayer.min.js"></script>
    <script src="assets/js/color-switcher.js"></script>
    <script src="assets/js/custom.js"></script>
</body>
</html>