<?php
namespace layouts\reserveViewTemplates;


class cart extends \DGZ_library\DGZ_HtmlView
{


function show()
{ ?>
	
    <!-- ==========================
    	SCROLL TOP - START 
    =========================== -->
    <div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
    <!-- ==========================
    	SCROLL TOP - END 
    =========================== -->
    

    
    <div id="page-wrapper"> <!-- PAGE - START -->
    
    
    <!-- ==========================
    	BREADCRUMB - START 
    =========================== -->
    <section class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <h2>Dorguzen</h2>
                    <p>Cart</p>
                </div>
                <div class="col-xs-6">
                    <ol class="breadcrumb">
                        <li><a href="index.phtml">Home</a></li>
                        <li class="active">Cart</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
	<!-- ==========================
    	BREADCRUMB - END 
    =========================== -->
    
    <!-- ==========================
    	MY ACCOUNT - START 
    =========================== -->
    <section class="content account">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <article class="account-content">
                        
                        <form>
                            <div class="products-order shopping-cart">
                            	<div class="table-responsive">
                                    <table class="table table-products">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th>Product</th>
                                                <th>Unit Price</th>
                                                <th>Quantity</th>
                                                <th>Subtotal</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td class="col-xs-1"><img src="assets/images/products/product-1.jpg" alt="" class="img-responsive"></td>
                                                <td class="col-xs-4 col-md-5"><h4><a href="single-product.html">Fusce Aliquam</a><small>M, Black, Esprit</small></h4></td>
                                                <td class="col-xs-2 text-center"><span>$30</span></td>
                                                <td class="col-xs-2 col-md-1"><div class="form-group"><input type="text" class="form-control" value="2"></div></td>
                                                <td class="col-xs-2 text-center"><span><b>$60</b></span></td>
                                                <td class="col-xs-1 text-center"><a href="" class="btn btn-primary"><i class="fa fa-times"></i></a></td>
                                            </tr>
                                            <tr>
                                                <td class="col-xs-1"><img src="assets/images/products/product-2.jpg" alt="" class="img-responsive"></td>
                                                <td class="col-xs-4 col-md-5"><h4><a href="single-product.html">Fusce Aliquam</a><small>M, Black, Esprit</small></h4></td>
                                                <td class="col-xs-2 text-center"><span>$80</span></td>
                                                <td class="col-xs-2 col-md-1"><div class="form-group"><input type="text" class="form-control" value="2"></div></td>
                                                <td class="col-xs-2 text-center"><span><b>$160</b></span></td>
                                                <td class="col-xs-1 text-center"><a href="" class="btn btn-primary"><i class="fa fa-times"></i></a></td>
                                            </tr>
                                            <tr>
                                                <td class="col-xs-1"><img src="assets/images/products/product-3.jpg" alt="" class="img-responsive"></td>
                                                <td class="col-xs-4 col-md-5"><h4><a href="single-product.html">Fusce Aliquam</a><small>M, Black, Esprit</small></h4></td>
                                                <td class="col-xs-2 text-center"><span>$95</span></td>
                                                <td class="col-xs-2 col-md-1"><div class="form-group"><input type="text" class="form-control" value="1"></div></td>
                                                <td class="col-xs-2 text-center"><span><b>$95</b></span></td>
                                                <td class="col-xs-1 text-center"><a href="" class="btn btn-primary"><i class="fa fa-times"></i></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            	<a href="products.html" class="btn btn-inverse">Continue Shopping</a>
                                <a href="" class="btn btn-inverse update-cart">Update Shopping Cart</a>
                            </div>
                        
                            <div class="box">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <h5>Enter your coupon code if you have one.</h5>
                                        <div class="input-group">
                                            <input type="email" class="form-control" placeholder="Discount code">
                                            <span class="input-group-btn">
                                                <button class="btn btn-primary" type="button">Apply Coupon</button>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-sm-4 col-sm-offset-2">
                                        <ul class="list-unstyled order-total">
                                            <li>Total products<span>$315.00</span></li>
                                            <li>Discount<span>- $25.00</span></li>
                                            <li>Subtotal<span class="total">$290.00</span></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix">
                                <a href="<?=$this->controller->settings->getFileRootPath()?>components/cart" class="btn btn-primary btn-lg pull-right ">Checkout</a>
                            </div>
                        </form>

                    </article>
                </div>
            </div> 
        </div>
    </section>
    <!-- ==========================
    	MY ACCOUNT - END 
    =========================== -->



        </div> <!-- PAGE - END -->

<?php }
}
?>