<!DOCTYPE html>
<html>
<head>
    <!-- ==========================
    	Meta Tags 
    =========================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- ==========================
    	Title 
    =========================== -->
    <title>uMarket - The easiest way to shop</title>
        
    <!-- ==========================
    	Fonts 
    =========================== -->
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,900,800' rel='stylesheet' type='text/css'>

    <!-- ==========================
    	CSS 
    =========================== -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="http://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
    <link href="assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="assets/css/dragtable.css" rel="stylesheet" type="text/css">
    <link href="assets/css/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="assets/css/animate.css" rel="stylesheet" type="text/css">
    <link href="assets/css/color-switcher.css" rel="stylesheet" type="text/css">
    <link href="assets/css/custom.css" rel="stylesheet" type="text/css">
    <link href="assets/css/color/red.css" id="main-color" rel="stylesheet" type="text/css">
    
    <!-- ==========================
    	JS 
    =========================== -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>
	
    <!-- ==========================
    	SCROLL TOP - START 
    =========================== -->
    <div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
    <!-- ==========================
    	SCROLL TOP - END 
    =========================== -->
    
	<!-- ==========================
    	COLOR SWITCHER - START 
    =========================== -->
	<div id="color-switcher">
        <div id="toggle-switcher"><i class="fa fa-gear"></i></div>
        <span>Color Scheme:</span>
        <ul class="list-unstyled list-inline">
            <li id="red" data-toggle="tooltip" data-placement="top" title="" data-original-title="Red"></li>
            <li id="purple" data-toggle="tooltip" data-placement="top" title="" data-original-title="Purple"></li>
            <li id="yellow" data-toggle="tooltip" data-placement="top" title="" data-original-title="Yellow"></li>
            <li id="blue" data-toggle="tooltip" data-placement="top" title="" data-original-title="Blue"></li>
            <li id="dark-blue" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dark Blue"></li>
            <li id="orange" data-toggle="tooltip" data-placement="top" title="" data-original-title="Orange"></li>
            <li id="green" data-toggle="tooltip" data-placement="top" title="" data-original-title="Green"></li>
            <li id="brown" data-toggle="tooltip" data-placement="top" title="" data-original-title="Brown"></li>
            <li id="dark-red" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dark Red"></li>
            <li id="light-green" data-toggle="tooltip" data-placement="top" title="" data-original-title="Light Green"></li>
        </ul>
    </div>
	<!-- ==========================
    	COLOR SWITCHER - END 
    =========================== -->
    
    <div id="page-wrapper"> <!-- PAGE - START -->
    
	<!-- ==========================
    	HEADER - START 
    =========================== -->
	<div class="top-header hidden-xs">
    	<div class="container">
            <div class="row">
                <div class="col-sm-5">
                    <ul class="list-inline contacts">
                        <li><i class="fa fa-envelope"></i> help@umarket.com</li>
                        <li><i class="fa fa-phone"></i> 754 213 456</li>
                    </ul>
                </div>
                <div class="col-sm-7 text-right">
                    <ul class="list-inline links">
                        <li><a href="my-account.html">My account</a></li>
                        <li><a href="checkout.html">Checkout</a></li>
                        <li><a href="wishlist.html">Wishlist (5)</a></li>
                        <li><a href="compare.html">Compare (3)</a></li>
                        <li><a href="signin.html">Logout</a></li>
                    </ul>
                    <ul class="list-inline languages hidden-sm">
                    	<li><a href="#"><img src="assets/images/flags/cz.png" alt="cs_CZ"></a></li>
                        <li><a href="#"><img src="assets/images/flags/us.png" alt="en_US"></a></li>
                        <li><a href="#"><img src="assets/images/flags/de.png" alt="de_DE"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <header class="navbar navbar-default navbar-static-top">
    	<div class="container">
            <div class="navbar-header">
                <a href="index.html" class="navbar-brand"><span>u</span>Market</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></button>
            </div>
            <div class="navbar-collapse collapse">
            	<p class="navbar-text hidden-xs hidden-sm">The easiest way to shop</p>
            	<ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Home</a>
                      	<ul class="dropdown-menu">
                        	<li><a href="index.html">Homepage 1</a></li>
                            <li><a href="homepage-2.html">Homepage 2</a></li>
                            <li><a href="homepage-3.html">Homepage 3<span class="label label-warning pull-right">Updated</span></a></li>
                            <li><a href="homepage-4.html">Homepage 4</a></li>
                            <li><a href="homepage-5.html">Homepage 5<span class="label label-danger pull-right">New</span></a></li>
                            <li><a href="homepage-6.html">Homepage 6<span class="label label-danger pull-right">New</span></a></li>
                      	</ul>
                    </li>
                    <li class="dropdown megamenu">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Eshop</a>
                      	<ul class="dropdown-menu">
                            <li class="col-sm-4 col-md-3">
                            	<ul class="list-unstyled">
                                	<li class="title">Men <span class="label label-danger pull-right">HOT</span></li>
                                    <li><a href="products.html">Sweatshirts & Jackets</a></li>
                                    <li><a href="products.html">Caps and Hats</a></li>
                                    <li><a href="products.html">Ties</a></li>
                                    <li><a href="products.html">Scarves</a></li>
                                    <li><a href="products.html">Shirts</a></li>
                                    <li><a href="products.html">Jeans</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4 col-md-3">
                            	<ul class="list-unstyled">
                                	<li class="title">Women <span class="label label-info pull-right">30% OFF SALE</span></li>
                                    <li><a href="products.html">Jackets & Coats</a></li>
                                    <li><a href="products.html">Jumpers & cardigans</a></li>
                                    <li><a href="products.html">Jeans</a></li>
                                    <li><a href="products.html">Trousers</a></li>
                                    <li><a href="products.html">Dresses</a></li>
                                    <li><a href="products.html">Long Sleeve Tops</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4 col-md-3">
                            	<ul class="list-unstyled">
                                	<li class="title">Accessories</li>
                                    <li><a href="products.html">Sunglasses</a></li>
                                    <li><a href="products.html">Watches</a></li>
                                    <li><a href="products.html">Umbrellas</a></li>
                                    <li><a href="products.html">Bags & Wallets</a></li>
                                    <li><a href="products.html">Fashion Jewellery</a></li>
                                    <li><a href="products.html">Belts</a></li>
                                </ul>
                            </li>
                            <li class="hidden-xs hidden-sm col-md-3">
                            	<img src="assets/images/megamenu.png" class="img-responsive center-block" alt="">
                            </li>
                      	</ul>
                    </li>
                    <li class="dropdown megamenu">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Pages</a>
                      	<ul class="dropdown-menu">
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                	<li class="title">Eshop</li>
                                    <li><a href="products.html">Products</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="compare.html">Compare</a></li>
                                    <li><a href="single-product.html">One Product</a></li>
                                    <li><a href="stores.html">Stores</a></li>
                                    <li><a href="about-shop.html">About Shop</a></li>
                                    <li><a href="lookbook.html">Lookbook</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                	<li class="title">Account</li>
                                    <li><a href="my-account.html">My Account<span class="label label-warning pull-right">Updated</span></a></li>
                                    <li><a href="profile.html">Profile</a></li>
                                    <li><a href="orders.html">Ordres</a></li>
                                    <li><a href="wishlist.html">Wishlist</a></li>
                                    <li><a href="address.html">Address</a></li>
                                    <li><a href="warranty-claims.html">Warranty Claims<span class="label label-danger pull-right">New</span></a></li>
                                    <li><a href="signup.html">Sign Up</a></li>
                                    <li><a href="signin.html">Sign In</a></li>
                                    <li><a href="lost-password.html">Lost Password</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                	<li class="title">Other Pages</li>
                                    <li><a href="blog.html">Blog</a></li>
                                    <li><a href="single-post.html">One Blog Post</a></li>
                                    <li><a href="single-order.html">Order Detail</a></li>
                                    <li><a href="downloads.html">Downloads<span class="label label-danger pull-right">New</span></a></li>
                                    <li><a href="faq.html">FAQ</a></li>
                                    <li><a href="privacy-policy.html">Privacy Policy</a></li>
                                    <li><a href="terms-conditions.html">Terms & Conditions</a></li>
                                    <li><a href="404.html">404 Error</a></li>
                                    <li><a href="email-template.html" target="_blank">Email Template</a></li>
                                </ul>
                            </li>
                      	</ul>
                    </li>
                    <li class="dropdown megamenu">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Components<span class="label label-danger pull-right">New</span></a>
                      	<ul class="dropdown-menu">
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                    <li><a href="components.html#headings">Headings</a></li>
                                    <li><a href="components.html#paragraphs">Paragraphs</a></li>
                                    <li><a href="components.html#lists">Lists</a></li>
                                    <li><a href="components.html#tabs">Tabs</a></li>
                                    <li><a href="components.html#accordition">Accordition</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                    <li><a href="components.html#collapse">Collapse</a></li>
                                    <li><a href="components.html#buttons">Buttons</a></li>
                                    <li><a href="components.html#tables">Tables</a></li>
                                    <li><a href="components.html#grids">Grids</a></li>
                                    <li><a href="components.html#responsive-video-audio">Responsive Video &amp; Audio</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                    <li><a href="components.html#alerts">Alerts</a></li>
                                    <li><a href="components.html#forms">Forms</a></li>
                                    <li><a href="components.html#labels">Labels</a></li>
                                    <li><a href="components.html#paginations">Paginations</a></li>
                                    <li><a href="components.html#carousels">Carousels</a></li>
                                </ul>
                            </li>
                      	</ul>
                    </li>
                    <li class="dropdown navbar-cart hidden-xs">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true"><i class="fa fa-shopping-cart"></i></a>
                      	<ul class="dropdown-menu">
                        	
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-3">
                                    	<img src="assets/images/products/product-1.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-9">
                                    	<h4><a href="single-product.html">Fusce Aliquam</a></h4>
                                        <p>1x - $20.00</p>
                                    	<a href="#" class="remove"><i class="fa fa-times-circle"></i></a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-3">
                                    	<img src="assets/images/products/product-2.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-9">
                                    	<h4><a href="single-product.html">Fusce Aliquam</a></h4>
                                        <p>1x - $20.00</p>
                                    	<a href="#" class="remove"><i class="fa fa-times-circle"></i></a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-3">
                                    	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-9">
                                    	<h4><a href="single-product.html">Fusce Aliquam</a></h4>
                                        <p>1x - $20.00</p>
                                    	<a href="#" class="remove"><i class="fa fa-times-circle"></i></a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-6">
                                    	<a href="cart.html" class="btn btn-primary btn-block">View Cart</a>
                                    </div>
                                    <div class="col-sm-6">
                                    	<a href="checkout.html" class="btn btn-primary btn-block">Checkout</a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                      	</ul>
                    </li>
                    <li class="dropdown navbar-search hidden-xs">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
                      	<ul class="dropdown-menu">
                        	<li>
                                <form>
                                    <div class="input-group input-group-lg">
                                        <input type="text" class="form-control" placeholder="Search ...">
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary" type="button">Search</button>
                                        </span>
                                    </div>
                                </form>
                            </li>
                      	</ul>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <!-- ==========================
    	HEADER - END 
    =========================== -->  
        
    <!-- ==========================
    	BREADCRUMB - START 
    =========================== -->
    <section class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <h2>uMarket</h2>
                    <p>Components</p>
                </div>
                <div class="col-xs-6">
                    <ol class="breadcrumb">
                        <li><a href="index.html">Home</a></li>
                        <li class="active">Components</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
	<!-- ==========================
    	BREADCRUMB - END 
    =========================== -->
    
    <!-- ==========================
    	COMPONENTS - START 
    =========================== -->
    <section class="content components">
        <div class="container">
            
            <article class="components-content">
                
                <!-- COMPONENTS:HEADINGS - START -->
                <h2 class="component-heading" id="headings"><i class="fa fa-header"></i>Headings</h2>
                <h1>H1 Heading <small>small text</small></h1>
                <h2>H2 Heading <small>small text</small></h2>
                <h3>H3 Heading <small>small text</small></h3>
                <h4>H4 Heading <small>small text</small></h4>
                <h5>H5 Heading <small>small text</small></h5>
                <h6>H6 Heading <small>small text</small></h6>
                <h1>H1 Heading with <span class="color">colored text</span></h1>
                <!-- COMPONENTS:HEADINGS - END -->
                
                <!-- COMPONENTS:PARAGRAPHS - START -->
                <h2 class="component-heading" id="paragraphs"><i class="fa fa-paragraph"></i>Paragraphs</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus metus, accumsan vitae vestibulum id, vulputate eget tellus. In auctor gravida dictum. Praesent magna lacus, pellentesque sit amet lobortis a, hendrerit ut enim. Quisque rhoncus tincidunt dui quis auctor. Vivamus id massa elementum, ultrices nisi ut, lobortis mauris. Integer sagittis pulvinar convallis.</p>
                <p class="text-capitalize">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus metus, accumsan vitae vestibulum id, vulputate eget tellus. In auctor gravida dictum. Praesent magna lacus, pellentesque sit amet lobortis a, hendrerit ut enim. Quisque rhoncus tincidunt dui quis auctor. Vivamus id massa elementum, ultrices nisi ut, lobortis mauris. Integer sagittis pulvinar convallis.</p>
                <p class="text-lowercase">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus metus, accumsan vitae vestibulum id, vulputate eget tellus. In auctor gravida dictum. Praesent magna lacus, pellentesque sit amet lobortis a, hendrerit ut enim. Quisque rhoncus tincidunt dui quis auctor. Vivamus id massa elementum, ultrices nisi ut, lobortis mauris. Integer sagittis pulvinar convallis.</p>
                <p class="text-uppercase">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus metus, accumsan vitae vestibulum id, vulputate eget tellus. In auctor gravida dictum. Praesent magna lacus, pellentesque sit amet lobortis a, hendrerit ut enim. Quisque rhoncus tincidunt dui quis auctor. Vivamus id massa elementum, ultrices nisi ut, lobortis mauris. Integer sagittis pulvinar convallis.</p>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus metus, accumsan vitae vestibulum id, vulputate eget tellus. In auctor gravida dictum. Praesent magna lacus, pellentesque sit amet lobortis a, hendrerit ut enim. Quisque rhoncus tincidunt dui quis auctor. Vivamus id massa elementum, ultrices nisi ut, lobortis mauris. Integer sagittis pulvinar convallis.</p>
                <p class="text-primary">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus metus, accumsan vitae vestibulum id, vulputate eget tellus. In auctor gravida dictum. Praesent magna lacus, pellentesque sit amet lobortis a, hendrerit ut enim. Quisque rhoncus tincidunt dui quis auctor. Vivamus id massa elementum, ultrices nisi ut, lobortis mauris. Integer sagittis pulvinar convallis.</p>
                <!-- COMPONENTS:PARAGRAPHS - END -->
                
                <!-- COMPONENTS:LISTS - START -->
                <h2 class="component-heading" id="lists"><i class="fa fa-list"></i>Lists</h2>
                <ul>
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>Nunc tellus metus, accumsan vitae vestibulum id</li>
                    <li>In auctor gravida dictum</li>
                    <li>Praesent magna lacus</li>
                </ul>
                <ol>
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>Nunc tellus metus, accumsan vitae vestibulum id</li>
                    <li>In auctor gravida dictum</li>
                    <li>Praesent magna lacus</li>
                </ol>
                <ul class="list-unstyled">
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>Nunc tellus metus, accumsan vitae vestibulum id</li>
                    <li>In auctor gravida dictum</li>
                    <li>Praesent magna lacus</li>
                </ul>
                <ul class="list-unstyled list-icons">
                    <li><i class="fa fa-trophy"></i>Lorem ipsum dolor sit amet</li>
                    <li><i class="fa fa-rocket"></i>Nunc tellus metus, accumsan vitae vestibulum id</li>
                    <li><i class="fa fa-star"></i>In auctor gravida dictum</li>
                    <li><i class="fa fa-gear"></i>Praesent magna lacus</li>
                </ul>
                <div class="widget widget-post-categories">
                    <ul class="list-unstyled">
                        <li><a href="#">Lorem ipsum dolor sit amet<span class="badge">54</span></a></li>
                        <li><a href="#">Nunc tellus metus, accumsan vitae vestibulum id<span class="badge">47</span></a></li>
                        <li><a href="#">In auctor gravida dictum<span class="badge">24</span></a></li>
                        <li><a href="#">Praesent magna lacus<span class="badge">12</span></a></li>
                    </ul>
                </div>
                <!-- COMPONENTS:LISTS - END -->
                
                <!-- COMPONENTS:TABS - START -->
                <h2 class="component-heading" id="tabs"><i class="fa fa-folder"></i>Tabs</h2>
                <div class="tabs">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class=""><a href="#demo-tabs-1" role="tab" data-toggle="tab" aria-controls="demo-tabs-1" aria-expanded="false">Demo Tab #1</a></li>
                        <li role="presentation" class="active"><a href="#demo-tabs-2" role="tab" data-toggle="tab" aria-controls="demo-tabs-2" aria-expanded="true">Demo Tab #2</a></li>
                        <li role="presentation" class=""><a href="#demo-tabs-3" role="tab" data-toggle="tab" aria-controls="demo-tabs-3" aria-expanded="false">Demo Tab #3</a></li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane" id="demo-tabs-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus metus, accumsan vitae vestibulum id, vulputate eget tellus. In auctor gravida dictum. Praesent magna lacus, pellentesque sit amet lobortis a, hendrerit ut enim.</p>
                        </div>
                        <div role="tabpanel" class="tab-pane active in" id="demo-tabs-2">
                            <p>Vivamus vulputate non lectus et efficitur. Suspendisse pulvinar neque eu nibh dapibus, nec porta mauris commodo. Integer pellentesque elit a tellus pellentesque, et varius erat lacinia. Nam imperdiet tellus sed pellentesque semper.</p>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="demo-tabs-3">
                            <p>Pellentesque euismod mattis turpis, et blandit massa faucibus a. Nulla interdum rutrum semper. Morbi egestas sollicitudin orci eget feugiat. In cursus, elit non interdum viverra, arcu dui tristique est, vel facilisis leo libero quis velit.</p>
                        </div>
                    </div>
                </div>
                <br><hr><br>
                <div class="tabs vertical-tabs">
                    <div class="row">
                        <div class="col-sm-3">
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class=""><a href="#demo-vertical-tabs-1" role="tab" data-toggle="tab" aria-controls="demo-vertical-tabs-1" aria-expanded="false">Demo Tab #1</a></li>
                                <li role="presentation" class="active"><a href="#demo-vertical-tabs-2" role="tab" data-toggle="tab" aria-controls="demo-vertical-tabs-2" aria-expanded="true">Demo Tab #2</a></li>
                                <li role="presentation" class=""><a href="#demo-vertical-tabs-3" role="tab" data-toggle="tab" aria-controls="demo-vertical-tabs-3" aria-expanded="false">Demo Tab #3</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-9">
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane" id="demo-vertical-tabs-1">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus metus, accumsan vitae vestibulum id, vulputate eget tellus. In auctor gravida dictum. Praesent magna lacus, pellentesque sit amet lobortis a, hendrerit ut enim.</p>
                                </div>
                                <div role="tabpanel" class="tab-pane active in" id="demo-vertical-tabs-2">
                                    <p>Vivamus vulputate non lectus et efficitur. Suspendisse pulvinar neque eu nibh dapibus, nec porta mauris commodo. Integer pellentesque elit a tellus pellentesque, et varius erat lacinia. Nam imperdiet tellus sed pellentesque semper.</p>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="demo-vertical-tabs-3">
                                    <p>Pellentesque euismod mattis turpis, et blandit massa faucibus a. Nulla interdum rutrum semper. Morbi egestas sollicitudin orci eget feugiat. In cursus, elit non interdum viverra, arcu dui tristique est, vel facilisis leo libero quis velit.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- COMPONENTS:TABS - END -->
                
                <!-- COMPONENTS:ACCORDITION - START -->
                <h2 class="component-heading" id="accordition"><i class="fa fa-bars"></i>Accordition</h2>
                <div class="panel-group" id="demo-accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-primary">
                        <div class="panel-heading" role="tab">
                            <h4 class="panel-title"><a role="button" data-toggle="collapse" data-parent="#demo-accordion" href="#demo-accordion-1" aria-expanded="true" aria-controls="demo-accordion-1">Demo Accordion #1</a></h4>
                        </div>
                        <div id="demo-accordion-1" class="panel-collapse collapse in" role="tabpanel">
                            <div class="panel-body">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-heading" role="tab">
                            <h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#demo-accordion" href="#demo-accordion-2" aria-expanded="false" aria-controls="demo-accordion-2">Demo Accordion #2</a></h4>
                        </div>
                        <div id="demo-accordion-2" class="panel-collapse collapse" role="tabpanel">
                            <div class="panel-body">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-heading" role="tab">
                            <h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#demo-accordion" href="#demo-accordion-3" aria-expanded="false" aria-controls="demo-accordion-3">Demo Accordion #3</a></h4>
                        </div>
                        <div id="demo-accordion-3" class="panel-collapse collapse" role="tabpanel">
                            <div class="panel-body">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.
                            </div>
                        </div>
                    </div>
                </div>
                <!-- COMPONENTS:ACCORDITION - END -->
                
                <!-- COMPONENTS:COLLAPSE - START -->
                <h2 class="component-heading" id="collapse"><i class="fa fa-plus"></i>Collapse</h2>
                <a class="btn btn-primary" role="button" data-toggle="collapse" href="#demo-collapse" aria-expanded="false" aria-controls="demo-collapse">Link with href</a>
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#demo-collapse" aria-expanded="false" aria-controls="demo-collapse">Button with data-target</button>
                <div class="collapse" id="demo-collapse">
                	<div class="well">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.</div>
                </div>
                <!-- COMPONENTS:COLLAPSE - END -->
                
                <!-- COMPONENTS:BUTTONS - START -->
                <h2 class="component-heading" id="buttons"><i class="fa fa-gear"></i>Buttons</h2>
                <div>
                    <a class="btn btn-default">Button Default</a>
                    <a class="btn btn-primary">Button Primary</a>
                    <a class="btn btn-inverse">Button Inverse</a>
                </div>
                <br>
                <div>
                    <a class="btn btn-info">Button Info</a>
                    <a class="btn btn-danger">Button Danger</a>
                    <a class="btn btn-warning">Button Warning</a>
                    <a class="btn btn-success">Button Success</a>
                </div>
                <br>
                <div>
                    <a class="btn btn-primary btn-xs">Button Primary</a>
                    <a class="btn btn-primary btn-sm">Button Primary</a>
                    <a class="btn btn-primary">Button Primary</a>
                    <a class="btn btn-primary btn-lg">Button Primary</a>
                </div>
                <br>
                <!-- COMPONENTS:BUTTONS - END -->
                
                <!-- COMPONENTS:TABLES - START -->
                <h2 class="component-heading" id="tables"><i class="fa fa-table"></i>Tables</h2>
                <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Number</th>
                            <th>First Name</th>
                            <th>Last Name</th>		
                            <th>Points</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>Eve</td>
                            <td>Jackson</td>		
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>John</td>
                            <td>Doe</td>		
                            <td>80</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Adam</td>
                            <td>Johnson</td>		
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>Jill</td>
                            <td>Smith</td>		
                            <td>50</td>
                        </tr>
                    </tbody>
                </table>
                </div>
                
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Number</th>
                            <th>First Name</th>
                            <th>Last Name</th>		
                            <th>Points</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>Eve</td>
                            <td>Jackson</td>		
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>John</td>
                            <td>Doe</td>		
                            <td>80</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Adam</td>
                            <td>Johnson</td>		
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>Jill</td>
                            <td>Smith</td>		
                            <td>50</td>
                        </tr>
                    </tbody>
                </table>
                <!-- COMPONENTS:TABLES - END -->
                
                <!-- COMPONENTS:GRIDS - START -->
                <h2 class="component-heading" id="grids"><i class="fa fa-th"></i>Grids</h2>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="default-style">
                            <h4>Full Width</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt turpis nec justo sollicitudin vestibulum.</p>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-6">
                        <div class="default-style">
                            <h4>One Half</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt turpis nec justo sollicitudin vestibulum.</p>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="default-style">
                            <h4>One Half</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt turpis nec justo sollicitudin vestibulum.</p>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-4">
                        <div class="default-style">
                            <h4>One Third</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                    <div class="col-xs-8">
                        <div class="default-style">
                            <h4>Two Third</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt turpis nec justo sollicitudin vestibulum.</p>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-3">
                        <div class="default-style">
                            <h4>One Fourth</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur.</p>
                        </div>
                    </div>
                    <div class="col-xs-9">
                        <div class="default-style">
                            <h4>Three Fourth</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt turpis nec justo sollicitudin vestibulum.</p>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-2">
                        <div class="default-style">
                            <h4>One Sixth</h4>
                        </div>
                    </div>
                    <div class="col-xs-10">
                        <div class="default-style">
                            <h4>Five Sixth</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt turpis nec justo sollicitudin vestibulum.</p>
                        </div>
                    </div>
                </div>
                
                <h4>Grid Layouts with Offset</h4>
                <div class="row">
                    <div class="col-xs-6 col-xs-offset-6">
                        <div class="default-style">
                            <h4>One Half With Offset (Half)</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt turpis nec justo sollicitudin vestibulum.</p>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-6 col-xs-offset-3">
                        <div class="default-style">
                            <h4>One Half With Offset (Fourth)</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tincidunt turpis nec justo sollicitudin vestibulum.</p>
                        </div>
                    </div>
                </div>
                
                <h4>Grid Layouts without Padding (class "row-no-padding")</h4>
                <div class="row row-no-padding">
                    <div class="col-xs-2">
                        <div class="default-style">
                            <h4>1</h4>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <div class="default-style">
                            <h4>2</h4>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <div class="default-style">
                            <h4>3</h4>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <div class="default-style">
                            <h4>4</h4>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <div class="default-style">
                            <h4>5</h4>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <div class="default-style">
                            <h4>6</h4>
                        </div>
                    </div>
                </div>
                
                <div class="row row-no-padding hidden-xs">
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>1</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>2</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>3</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>4</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>5</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>6</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>7</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>8</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>9</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>10</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>11</h4>
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <div class="default-style">
                            <h4>12</h4>
                        </div>
                    </div>
                </div>
                <!-- COMPONENTS:GRIDS - END -->
                
                <!-- COMPONENTS:RESPONSIVE VIDEO AND AUDIO - START -->
                <h2 class="component-heading" id="responsive-video-audio"><i class="fa fa-video-camera"></i>Responsive Video &amp; Audio</h2>
                <div class="row">
                	<div class="col-sm-6">
                        <div class="embed-responsive embed-responsive-16by9">
                            <iframe src="https://player.vimeo.com/video/120197450"></iframe>
                        </div>
                    </div>
                    <div class="col-sm-6">
                    	<br class="visible-xs">
                        <div class="embed-responsive embed-responsive-16by9">
                            <iframe src="https://www.youtube.com/embed/GUEZCxBcM78"></iframe>
                        </div>
                    </div>
                    <div class="col-xs-12">
                    	<br>
                        <div class="embed-responsive embed-responsive-audio">
                            <iframe height="166" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/147737117&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
                        </div>
                    </div>
                </div>
                <!-- COMPONENTS:RESPONSIVE VIDEO AND AUDIO - END -->

                <!-- COMPONENTS:ALERTS - START -->
                <h2 class="component-heading" id="alerts"><i class="fa fa-exclamation-triangle"></i>Alerts</h2>
                <div class="alert alert-success" role="alert"><b>Well done!</b> You successfully read this important alert message.</div>
                <div class="alert alert-info" role="alert"><b>Heads up!</b> This alert needs your attention, but it's not super important.</div>
                <div class="alert alert-warning" role="alert"><b>Warning!</b> Better check yourself, you're not looking too good.</div>
                <div class="alert alert-danger" role="alert"><b>Oh snap!</b> Change a few things up and try submitting again.</div>
                <div class="alert alert-warning alert-dismissible" role="alert">
                	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><i class="fa fa-times"></i></button>
               		<b>Warning!</b> Better check yourself, you're not looking too good.
                </div>
                <!-- COMPONENTS:ALERTS - END -->
                
                <!-- COMPONENTS:FORMS - START -->
                <h2 class="component-heading" id="forms"><i class="fa fa-search"></i>Forms</h2>
                <h3>Search Form</h3>
                <form>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search ...">
                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </form>
                <br>
                <br>
                <h3>Classic Form</h3>
                <form>
                    <div class="form-group">
                        <label class="control-label">First Name<span class="required">*</span></label>
                        <input type="text" class="form-control" placeholder="">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Last Name<span class="required">*</span></label>
                            <input type="text" class="form-control" placeholder="">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Email<span class="required">*</span></label>
                        <input type="email" class="form-control" placeholder="">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
                <br>
                <br>
                <h3>Horizontal Form</h3>
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-4 col-lg-3 control-label">First Name<span class="required">*</span></label>
                        <div class="col-md-6 col-lg-6">
                            <input type="text" class="form-control" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-lg-3 control-label">Last Name<span class="required">*</span></label>
                        <div class="col-md-6 col-lg-6">
                            <input type="text" class="form-control" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-lg-3 control-label">Email<span class="required">*</span></label>
                        <div class="col-md-8 col-lg-9">
                            <input type="email" class="form-control" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-4 col-md-8 col-lg-offset-3 col-lg-9">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
                <br>
                <br>
                <h3>Inline Form</h3>
                <form class="form-inline">
                    <div class="form-group">
                        <label class="control-label">First Name<span class="required">*</span></label>
                        <input type="text" class="form-control" placeholder="">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Last Name<span class="required">*</span></label>
                            <input type="text" class="form-control" placeholder="">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Email<span class="required">*</span></label>
                        <input type="email" class="form-control" placeholder="">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>

                <!-- COMPONENTS:FORMS - END -->
                
                <!-- COMPONENTS:LABELS - START -->
                <h2 class="component-heading" id="labels"><i class="fa fa-font"></i>Labels</h2>
                <div>
                	<span class="label label-default">Default</span>
                    <span class="label label-primary">Primary</span>
                    <span class="label label-success">Success</span>
                    <span class="label label-info">Info</span>
                    <span class="label label-warning">Warning</span>
                    <span class="label label-danger">Danger</span>
                </div>
                <br>
                <div class="tags">
                    <span class="label"><i class="fa fa-tag"></i><a href="#">book</a></span>
                    <span class="label"><i class="fa fa-tag"></i><a href="#">music</a></span>
                    <span class="label"><i class="fa fa-tag"></i><a href="#">nature</a></span>
                    <span class="label"><i class="fa fa-tag"></i><a href="#">read</a></span>
                    <span class="label"><i class="fa fa-tag"></i><a href="#">songs</a></span>
                    <span class="label"><i class="fa fa-tag"></i><a href="#">sunshine</a></span>
                </div>
                <!-- COMPONENTS:LABELS - END -->
                
                <!-- COMPONENTS:PAGINATIONS - START -->
                <h2 class="component-heading" id="paginations"><i class="fa fa-archive"></i>Paginations</h2>
                <ul class="pagination pagination-lg">
                    <li><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>
                <br>
                <ul class="pagination">
                    <li><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>
                <br>
                <ul class="pagination pagination-sm">
                    <li><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>
                <!-- COMPONENTS:PAGINATIONS - END -->
                
                <!-- COMPONENTS:CAROUSELS - START -->
                <h2 class="component-heading" id="carousels"><i class="fa fa-spinner"></i>Carousels</h2>
                <h3>Defualt Carousel</h3>
                <div id="default-carousel" class="nav-inside">
                    <div class="item" style="background-image:url(assets/images/slide-1.jpg);"></div>
                    <div class="item" style="background-image:url(assets/images/slide-2.jpg);"></div>
                    <div class="item" style="background-image:url(assets/images/slide-4.jpg);"></div>
                    <div class="item" style="background-image:url(assets/images/slide-5.jpg);"></div>
                </div>
                <br>
                <h3>Defualt Carousel (Fade Effect)</h3>
                <div id="default-carousel-fade" class="nav-inside">
                    <div class="item" style="background-image:url(assets/images/slide-1.jpg);"></div>
                    <div class="item" style="background-image:url(assets/images/slide-2.jpg);"></div>
                    <div class="item" style="background-image:url(assets/images/slide-4.jpg);"></div>
                    <div class="item" style="background-image:url(assets/images/slide-5.jpg);"></div>
                </div>
                <br>
                <h3>Brands Carousel</h3>
                <div id="brands-carousel">
                    <div class="item"><a href="lookbook.html"><img src="assets/images/clients/1.png" class="img-responsive" alt=""></a></div>
                    <div class="item"><a href="lookbook.html"><img src="assets/images/clients/2.png" class="img-responsive" alt=""></a></div>
                    <div class="item"><a href="lookbook.html"><img src="assets/images/clients/3.png" class="img-responsive" alt=""></a></div>
                    <div class="item"><a href="lookbook.html"><img src="assets/images/clients/4.png" class="img-responsive" alt=""></a></div>
                    <div class="item"><a href="lookbook.html"><img src="assets/images/clients/5.png" class="img-responsive" alt=""></a></div>
                    <div class="item"><a href="lookbook.html"><img src="assets/images/clients/6.png" class="img-responsive" alt=""></a></div>
                    <div class="item"><a href="lookbook.html"><img src="assets/images/clients/7.png" class="img-responsive" alt=""></a></div>
                </div>
                <!-- COMPONENTS:CAROUSELS - END -->
                
            </article>
                
        </div>
    </section>
    <!-- ==========================
    	COMPONENTS - END 
    =========================== -->
    
    <!-- ==========================
    	FOOTER - START 
    =========================== -->
    <footer class="navbar navbar-default">
    	<div class="container">
        	<div class="row">
                <div class="col-sm-3 col-xs-6">
                	<div class="footer-widget footer-widget-contacts">
                    	<h4>Contacts</h4>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-envelope"></i> help@umarket.com</li>
                            <li><i class="fa fa-phone"></i> 754 213 456</li>
                            <li><i class="fa fa-map-marker"></i> 40°44'00.9"N 73°59'43.4"W</li>
                            <li class="social">
                            	<a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-tumblr"></i></a>
                            </li>
                        </ul>
                	</div>
                </div>
                <div class="col-sm-3 col-xs-6">
                	<div class="footer-widget footer-widget-links">
                    	<h4>Information</h4>
                        <ul class="list-unstyled">
                        	<li><a href="about-shop.html">About Shop</a></li>
                            <li><a href="stores.html">Our Stores</a></li>
                            <li><a href="terms-conditions.html">Terms & Conditions</a></li>
                            <li><a href="privacy-policy.html">Privacy Policy</a></li>
                            <li><a href="faq.html">FAQ</a></li>
                            <li><a href="my-account.html">My account</a></li>
                        </ul>
                	</div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="footer-widget footer-widget-twitter">
                    	<h4>Recent tweets</h4>
                        <div id="twitter-wrapper"></div>
                	</div>
                </div>
                <div class="col-sm-3 col-xs-6">
                	<div class="footer-widget footer-widget-facebook">
                    	<h4>Facebook Page</h4>
                        <ul class="list-unstyled row row-no-padding">
                        	<li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_01.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_02.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_03.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_04.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_01.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_02.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_03.jpg" class="img-responsive" alt=""></a></li>
                            <li class="col-xs-3"><a href="#"><img src="assets/images/avatar/avatar_04.jpg" class="img-responsive" alt=""></a></li>
                        </ul>
                        <p>45,500 Likes  <a href="#" class="btn btn-default btn-sm"><i class="fa fa-thumbs-up"></i>Like</a></p>
                	</div>
                </div>
            </div>
            <div class="footer-bottom">
            	<div class="row">
                    <div class="col-sm-6">
                        <p class="copyright">© Umarket 2016 All right reserved.</p>
                        <p class="copyright">Designed by <a href="http://www.pixelized.cz/" target="_blank">Pixelized Studio.</a></p>
                    </div>
                    <div class="col-sm-6">
                        <ul class="list-inline payment-methods">
                        	<li><i class="fa fa-cc-amex"></i></li>
                            <li><i class="fa fa-cc-diners-club"></i></li>
                            <li><i class="fa fa-cc-discover"></i></li>
                            <li><i class="fa fa-cc-jcb"></i></li>
                            <li><i class="fa fa-cc-mastercard"></i></li>
                            <li><i class="fa fa-cc-paypal"></i></li>
                            <li><i class="fa fa-cc-stripe"></i></li>
                            <li><i class="fa fa-cc-visa"></i></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ==========================
    	FOOTER - END 
    =========================== -->
    
    <!-- ==========================
    	MODAL ADVERTISING  - START 
    =========================== -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modalAdvertising">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                    	<div class="col-sm-8">
                        	<h3>Dicount 10%</h3>
                        	<p>Enter your email address and get 10% discount for your first purchase.</p>
                            <form>
                                <div class="input-group">
                                    <input type="email" class="form-control" placeholder="Email Address">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="button">Submit</button>
                                    </span>
                                </div>
                            </form>
                            <div class="checkbox">  
                                <input id="modal-hide" type="checkbox" value="hidden">  
                                <label for="modal-hide">Don't show this popup again</label>
                            </div>
                        </div>
                        <div class="col-sm-4 hidden-xs">
                        	<img src="assets/images/lookbook-1.png" class="img-responsive" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<!-- ==========================
    	MODAL ADVERTISING - END 
    =========================== -->
    
    </div> <!-- PAGE - END -->
    
   	<!-- ==========================
    	JS 
    =========================== -->        
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=true"></script>
	<script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/bootstrap-hover-dropdown.min.js"></script>
    <script src="assets/js/SmoothScroll.js"></script>
    <script src="assets/js/jquery.dragtable.js"></script>
    <script src="assets/js/jquery.card.js"></script>
    <script src="assets/js/owl.carousel.min.js"></script>
    <script src="assets/js/twitterFetcher_min.js"></script>
    <script src="assets/js/jquery.mb.YTPlayer.min.js"></script>
    <script src="assets/js/color-switcher.js"></script>
    <script src="assets/js/custom.js"></script>
</body>
</html>