<?php
namespace layouts\reserveViewTemplates;


class emailTemplate extends \DGZ_library\DGZ_HtmlView
{


function show()
{ ?>

	   
    <!-- ==========================
    	EMAIL TEMPLATE - START 
    =========================== -->
    <table width="100%" cellpadding="0" cellspacing="0" border="0"  style="background-image:url(assets/images/pattern.png); margin:0; padding:0;">
        <tbody>
            <tr>
                <td>
                	<!-- EMAIL HEADER - START -->
                    <table width="600" cellpadding="0" cellspacing="0" border="0" align="center">
                        <tbody>
                            <tr>
                                <td bgcolor="#333333">
                                    <table width="570" cellpadding="0" cellspacing="0" border="0" align="center">
                                        <tbody>
                                            <tr>
                                            	<td width="100%" height="5"></td>
                                            </tr>
                                            <tr>
                                            	<td width="100%" align="center" style="color:#FFFFFF;font-family:Verdana,Geneva,sans-serif;font-size:50px;line-height:150%;">Dorguzen</td>
                                            </tr>
                                            <tr>
                                            	<td width="100%" align="center" style="color:#888888;font-family:Helvetica,Arial,sans-serif;font-size:18px;line-height:150%;">Toolkit for web building</td>
                                            </tr>
                                            <tr>
                                            	<td width="100%" height="20"></td>
                                            </tr>
                                        </tbody>
                                	</table>
                            	</td>
                            </tr>
                        </tbody>
                    </table>
                    <!-- EMAIL HEADER - END -->
                    
                    <!-- EMAIL BODY - START -->
                    <table width="600" cellpadding="0" cellspacing="0" border="0" align="center">
                        <tbody>
                            <tr>
                                <td bgcolor="#FFFFFF">
                                    <table width="570" cellpadding="0" cellspacing="0" border="0" align="center">
                                        <tbody>
                                            <tr>
                                            	<td height="15"></td>
                                            </tr>
                                            <tr>
                                            	<td align="center">
                                                	<img src="assets/images/showcase.png" alt="" width="500">
                                                </td>
                                            </tr>
                                            <tr>
                                            	<td align="center">
                                                	<h3 style="color:#555555;font-family:Helvetica,Arial,sans-serif;font-size:24px;line-height:150%;margin-bottom:0">Responsive E-commerce theme</h3>
                                                    <p style="color:#999999;font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:150%;">Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. <a href="#" style="color:#E87169;">Vestibulum tortor.</a>Vestibulum tortor quam, feugiat vitae, ultricies eget.</p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center">
                                                    <table border="0" cellpadding="0" cellspacing="0" width="35%" style="background-color:#E87169;">
                                                        <tbody>
                                                            <tr>
                                                                <td align="center" style="padding-top:10px;padding-bottom:10px;padding-right:10px;padding-left:10px;">
                                                                    <a href="#" style="color:#FFFFFF;text-decoration:none;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:700;line-height:150%;" target="_blank">Buy Now ($16)</a>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            <tr>
                                            	<td height="30"></td>
                                            </tr>
                                            <tr>
                                            	<td height="1" bgcolor="#f0f0f0"></td>
                                            </tr>
                                            <tr>
                                            	<td height="30"></td>
                                            </tr>
                                            <tr>
                                            	<td>
                                                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                                        <tbody>
                                                            <tr>
                                                                <td>
                                                                    <table border="0" cellpadding="0" cellspacing="0" width="285">
                                                                        <tbody>
                                                                            <tr>
                                                                                <td align="left">
                                                                                    <img src="assets/images/lookbook-1.png" alt="" width="270">
                                                                                </td>
                                                                            </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                                <td>
                                                                    <table border="0" cellpadding="0" cellspacing="0" width="285">
                                                                        <tbody>
                                                                            <tr>
                                                                                <td>
                                                                                    <h3 style="color:#666666;font-family:Helvetica,Arial,sans-serif;font-size:18px;line-height:150%;margin-bottom:0;">Box with left image</h3>
                                                                                    <p style="color:#999999;font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:150%;">Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Vestibulum tortor quam, feugiat vitae, ultricies eget.</p>
                                                                                </td>
                                                                            </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            <tr>
                                            	<td height="30"></td>
                                            </tr>
                                            <tr>
                                            	<td height="1" bgcolor="#f0f0f0"></td>
                                            </tr>
                                            <tr>
                                            	<td height="30"></td>
                                            </tr>
                                            <tr>
                                            	<td>
                                                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                                        <tbody>
                                                            <tr>
                                                                <td>
                                                                    <table border="0" cellpadding="0" cellspacing="0" width="285">
                                                                        <tbody>
                                                                            <tr>
                                                                                <td>
                                                                                    <h3 style="color:#666666;font-family:Helvetica,Arial,sans-serif;font-size:18px;line-height:150%;margin-bottom:0;">Box with right image</h3>
                                                                                    <p style="color:#999999;font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:150%;">Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Vestibulum tortor quam, feugiat vitae, ultricies eget.</p>
                                                                                </td>
                                                                            </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                                <td>
                                                                    <table border="0" cellpadding="0" cellspacing="0" width="285">
                                                                        <tbody>
                                                                            <tr>
                                                                                <td align="right">
                                                                                    <img src="assets/images/lookbook-2.png" alt="" width="270">
                                                                                </td>
                                                                            </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            <tr>
                                            	<td height="15"></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                             </tr>
                             <tr>
                                <td bgcolor="#E87169">
                                    <table width="570" cellpadding="0" cellspacing="0" border="0" align="center">
                                        <tbody>
                                            <tr>
                                            	<td height="15"></td>
                                            </tr>
                                            <tr>
                                                <td align="center">
                                                    <p style="color:#FFFFFF;font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:150%;">Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Vestibulum tortor quam, feugiat vitae, ultricies eget.</p>
                                                </td>
                                            </tr>
                                            <tr>
                                            	<td height="10"></td>
                                            </tr>
                                            <tr>
                                                <td align="center">
                                                	<a href="#"><img src="assets/icons/icon_facebook_circle_gray.png" width="48"></a>
                                                    <a href="#"><img src="assets/icons/icon_twitter_circle_gray.png" width="48"></a>
                                                    <a href="#"><img src="assets/icons/icon_google_circle_gray.png" width="48"></a>
                                                    <a href="#"><img src="assets/icons/icon_instagram_circle_gray.png" width="48"></a>
                                                    <a href="#"><img src="assets/icons/icon_linkedin_circle_gray.png" width="48"></a>
                                                    <a href="#"><img src="assets/icons/icon_youtube_circle_gray.png" width="48"></a>
                                                </td>
                                            </tr>
                                            <tr>
                                            	<td height="25"></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <!-- EMAIL BODY - END -->
                    
                    <!-- EMAIL FOOTER - START -->
                    <table width="600" cellpadding="0" cellspacing="0" border="0" align="center">
                        <tbody>
                            <tr>
                                <td>
                                    <table width="570" cellpadding="0" cellspacing="0" border="0" align="center">
                                        <tbody>
                                            <tr>
                                            	<td height="20"></td>
                                            </tr>
                                            <tr>
                                            	<td align="center">
                                                	<p style="color:#999999;font-family:Helvetica,Arial,sans-serif;font-size:14px;margin-top:0;">© Dorguzen All right reserved. Designed by <a href="http://www.gustavdigitals.com/" target="_blank" style="color:#E87169;text-decoration:none;">Nolimit Media.</a></p>
                                            	</td>
                                            </tr>
                                            <tr>
                                            	<td height="5"></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <!-- EMAIL FOOTER - END -->
                </td>
            </tr>
        </tbody>
    </table>
    <!-- ==========================
    	EMAIL TEMPLATE - END 
    =========================== -->

<?php }
}
?>