<?php 
ob_start();
//require_once('controllers/gen_access_timeout.inc.php');
include('controllers/title.inc.php');
include('controllers/config.inc.php');
?>
<!doctype html>
<html class="no-js" lang="en">
<head>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,600italic,700,700italic,300italic" rel="stylesheet" type="text/css">
<meta charset="utf-8">
<title>Gallery</title>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width, initial-scale=1">

    
    <!-- ==========================
        - START 
    =========================== -->
        <?php include('controllers/html_dependencies_top.inc.php'); ?>
    <!-- ==========================
         - END 
    =========================== --> 

</head>
<body>
<header>

<?=include('controllers/header.inc.php')?>    
    
</header>
<div class="main">
     <section class="hgroup">
          <div class="container">
               <h1>Masonry portfolio <small>or</small> photo gallery</h1>
               <h2>This is a mixture of portfolio items and photo gallery! We are using the Isotope Jquery plugin to filter results and Prettyphoto to open the lighbox. 
                    This is the<strong> Masonry Version</strong>, you should also check out the <a href="portfolio.html"><strong>strict version</strong></a>. All photos © by <a href="http://www.dimitragiannouka.com" target="_blank">Dimitra Giannouka</a>.</h2>
               <ul class="breadcrumb pull-right">
                    <li><a href="index.html">Home</a> </li>
                    <li class="active">Portfolio</li>
               </ul>
          </div>
     </section>
     <section>
          <div class="container">
               <ul class="portfolio_filters">
                    <li><a href="#" data-filter="*">show all</a></li>
                    <li><a href="#" data-filter=".cat_just_photos">just photos</a></li>
                    <li><a href="#" data-filter=".cat_projects">whole projects</a></li>
               </ul>
          </div>
     </section>
     <section class="portfolio_masonry">
          <div class="container">
               <div class="row isotope_portfolio_container">
                    <div class="cat_just_photos col-sm-4 col-md-4">
                         <div class="portfolio_item"> <a class="prettyPhoto" href="images/portfolio/t2.jpg"> <img src="images/portfolio/t2.jpg" alt="The title of the photo">
                              <div class="overlay">
                                   <div class="desc"> <i class="fa fa-resize-full"></i> </div>
                              </div>
                              </a> </div>
                    </div>
                    <div class="cat_projects col-sm-4 col-md-4">
                         <div class="portfolio_item"> <a href="portfolio_item.html"> <img src="images/portfolio/a6.jpg" alt="Title of the project">
                              <div class="overlay">
                                   <div class="desc"> <i class="fa fa-external-link"></i>
                                        <h3>Title of the project</h3>
                                        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
                                   </div>
                              </div>
                              </a> </div>
                    </div>
                    <div class="cat_just_photos col-sm-4 col-md-4">
                         <div class="portfolio_item"> <a class="prettyPhoto" href="images/portfolio/b3.jpg"> <img src="images/portfolio/b3.jpg" alt="The title of the photo">
                              <div class="overlay">
                                   <div class="desc"> <i class="fa fa-resize-full"></i> </div>
                              </div>
                              </a> </div>
                    </div>
                    <div class="cat_projects col-sm-4 col-md-4">
                         <div class="portfolio_item"> <a href="portfolio_item.html"> <img src="images/portfolio/a4.jpg" alt="Title of the project">
                              <div class="overlay">
                                   <div class="desc"> <i class="fa fa-external-link"></i>
                                        <h3>Title of the project</h3>
                                        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
                                   </div>
                              </div>
                              </a> </div>
                    </div>
                    <div class="cat_just_photos col-sm-4 col-md-4">
                         <div class="portfolio_item"> <a class="prettyPhoto" href="images/portfolio/p4.jpg"> <img src="images/portfolio/p4.jpg" alt="The title of the photo">
                              <div class="overlay">
                                   <div class="desc"> <i class="fa fa-resize-full"></i> </div>
                              </div>
                              </a> </div>
                    </div>
                    <div class="cat_projects col-sm-4 col-md-4">
                         <div class="portfolio_item"> <a href="portfolio_item.html"> <img src="images/portfolio/t4.jpg" alt="Title of the project">
                              <div class="overlay">
                                   <div class="desc"> <i class="fa fa-external-link"></i>
                                        <h3>Title of the project</h3>
                                        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
                                   </div>
                              </div>
                              </a> </div>
                    </div>
                    <div class="cat_just_photos col-sm-4 col-md-4">
                         <div class="portfolio_item"> <a class="prettyPhoto" href="images/portfolio/t3.jpg"> <img src="images/portfolio/t3.jpg" alt="The title of the photo">
                              <div class="overlay">
                                   <div class="desc"> <i class="fa fa-resize-full"></i> </div>
                              </div>
                              </a> </div>
                    </div>
                    <div class="cat_projects col-sm-4 col-md-4">
                         <div class="portfolio_item"> <a href="portfolio_item.html"> <img src="images/portfolio/a3.jpg" alt="Title of the project">
                              <div class="overlay">
                                   <div class="desc"> <i class="fa fa-external-link"></i>
                                        <h3>Title of the project</h3>
                                        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
                                   </div>
                              </div>
                              </a> </div>
                    </div>
               </div>
          </div>
     </section>

    
        
    <!-- ==========================
    	FOOTER - START 
    =========================== -->
        <?php include('controllers/footer.inc.php'); ?>
    <!-- ==========================
    	FOOTER - END 
    =========================== -->
    
    
</div>


    
    <!-- ==========================
        JS - START 
    =========================== -->
        <?php include('controllers/html_dependencies_bottom.inc.php'); ?>
    <!-- ==========================
        NEWSLETTER - END 
    =========================== -->
    
</body>
</html>