<?php
namespace layouts\reserveViewTemplates;


class index extends \DGZ_library\DGZ_HtmlView
{


function show()
{ ?>
	
    <!-- ==========================
    	SCROLL TOP - START 
    =========================== -->
    <div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
    <!-- ==========================
    	SCROLL TOP - END 
    =========================== -->
    

    
    <div id="page-wrapper"> <!-- PAGE - START -->
           
    <!-- ==========================
    	JUMBOTRON - START 
    =========================== -->
    <section class="content jumbotron jumbotron-full-height">
        <div id="homepage-2-carousel" class="nav-inside">
            
            <div class="item slide-1">
                <div class="slide-mask"></div>
                <div class="slide-body">
                    <div class="container">
                        <h1>Welcome to <span class="color">Sweeteaze</span></h1>
                        <h2>The home of online Lingerie</h2>
                        <a href="http://localhost/sweeteaze/products.phtml" class="btn btn-default btn-lg">Browse Catalog</a>
                        <a href="http://localhost/sweeteaze/contact.phtml" class="btn btn-inverse btn-lg">Contact us</a>
                    </div>
                </div>
            </div>
            <div class="item slide-2">
                <div class="slide-mask"></div>
                <div class="slide-body">
                    <div class="container">
                    	<h1 class="grey-background">Awesome Collections</h1>
                        <div><h2 class="color-background">Dresses, toys, more...</h2></div>
                        <ul class="list-unstyled">
                        	<li><i class="fa fa-check"></i>Reliable shipping</li>
                            <li><i class="fa fa-check"></i>Amazing Customer Service</li>
                            <li><i class="fa fa-check"></i>No Customs Or Duty Fees!</li>
                        </ul>
                    </div>
                </div>
            </div>
                        
        </div>
    </section>
    <!-- ==========================
    	JUMBOTRON - END 
    =========================== -->
    
    <!-- ==========================
    	SERVICES - START 
    =========================== -->
    <section class="content services services-3x border-top border-bottom">
        <div class="container">
        	<div class="row row-no-padding">
        
            
            	<!-- SERVICE - START -->
                <div class="col-xs-12 col-sm-4">
                    <div class="service">
                        <i class="fa fa-star"></i>
                        <h3>RELIABLE SHIPPING</h3>
                        <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                    </div>
                </div>
                <!-- SERVICE - END -->
                
                <!-- SERVICE - START -->
                <div class="col-xs-6 col-sm-4">
                    <div class="service">
                        <i class="fa fa-heart"></i>
                        <h3>AMAZING CUSTOMER SERVICE</h3>
                        <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                    </div>
                </div>
                <!-- SERVICE - END -->
                
                <!-- SERVICE - START -->
                <div class="col-xs-6 col-sm-4">
                    <div class="service">
                        <i class="fa fa-rocket"></i>
                        <h3>NO CUSTOMS OR DUTY FEES!</h3>
                        <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                    </div>
                </div>
                <!-- SERVICE - END -->
                
            </div>
            
        </div>
    </section>
    <!-- ==========================
    	SERVICES - END 
    =========================== -->
    
    <!-- ==========================
    	CATEGORIES - START 
    =========================== -->
    <section class="content categories">
        <div class="row row-no-padding">
        
            <!-- CATEGORY - START -->
            <div class="col-xs-4">
                <div class="category">
                    <a href="products.phtml">
                        <img src="assets/images/categories/category-2.jpg" class="img-responsive" alt="">
                        <div class="category-mask"></div>
                        <h3 class="category-title">Clothes <span>Collection</span></h3>
                    </a>
                </div>
            </div>
            <!-- CATEGORY - END -->
            
            <!-- CATEGORY - START -->
            <div class="col-xs-4">
                <div class="category">
                    <a href="products.phtml">
                        <img src="assets/images/categories/category-3.jpg" class="img-responsive" alt="">
                        <div class="category-mask"></div>
                        <h3 class="category-title">Costume <span>Collection</span></h3>
                    </a>
                </div>
            </div>
            <!-- CATEGORY - END -->
            
            <!-- CATEGORY - START -->
            <div class="col-xs-4">
                <div class="category">
                    <a href="products.phtml">
                        <img src="assets/images/categories/category-4.jpg" class="img-responsive" alt="">
                        <div class="category-mask"></div>
                        <h3 class="category-title">Toys <span>Collection</span></h3>
                    </a>
                </div>
            </div>
            <!-- CATEGORY - END -->
                            
        </div>
        
    </section>
    <!-- ==========================
    	CATEGORIES - END 
    =========================== -->
    
    <!-- ==========================
    	GRID PRODUCTS - START 
    =========================== -->
    <section class="content grid-products border-top">
        <div class="container">
        	 <div class="row">
             	
                <div class="col-xs-6 col-sm-3">
                    <article class="product-item">
                        <img src="assets/images/products/product-1.jpg" class="img-responsive" alt="">
                        <h3><a href="singleProduct.phtml">Sunny Tank Selected Femme</a></h3>
                        <div class="product-rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <span class="price">
                        	<del><span class="amount">£36.00</span></del>
                            <ins><span class="amount">£30.00</span></ins>
                        </span>
                    </article>
                </div>
                
                <div class="col-xs-6 col-sm-3">
                    <article class="product-item">
                        <img src="assets/images/products/product-2.jpg" class="img-responsive" alt="">
                        <h3><a href="singleProduct.phtml">Sunny Tank Selected Femme</a></h3>
                        <div class="product-rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <span class="price">
                        	<del><span class="amount">£36.00</span></del>
                            <ins><span class="amount">£30.00</span></ins>
                        </span>
                    </article>
                </div>
                
                <div class="col-xs-12 col-sm-3">
                    <ul class="list-unstyled small-product">
                    	
               			<!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-1.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                                <del><span class="amount">£36.00</span></del>
                            	<ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-2.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                            	<del><span class="amount">£36.00</span></del>
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                            	<del><span class="amount">£36.00</span></del>
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                            	<del><span class="amount">£36.00</span></del>
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                    </ul>
                    
                </div>
                
                <div class="col-xs-12 col-sm-3">
                    <ul class="list-unstyled small-product">
                    	
               			<!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-1.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                                <del><span class="amount">£36.00</span></del>
                            	<ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-2.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                            	<del><span class="amount">£36.00</span></del>
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                            	<del><span class="amount">£36.00</span></del>
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                            	<del><span class="amount">£36.00</span></del>
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                    </ul>
                    
                </div>
             </div>     	
        </div>
    </section>
    <!-- ==========================
    	GRID PRODUCTS - END 
    =========================== -->
    
    <!-- ==========================
    	NOTIFICATION - START 
    =========================== -->
    <section class="content pattern notification">
        <div class="container">
        	<div class="row">
            	<div class="col-sm-4">
                    <span>The new amazing collection is here!</span>
                    <a href="#" class="btn btn-default btn-lg">Let's Go</a>
                </div>
                <div class="col-sm-8">
                    <h3>Summer Collection 2015</h3>
                    <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Vestibulum tortor quam, feugiat vitae, ultricies eget.</p>
        		</div>
            </div>
        </div>
    </section>
     <!-- ==========================
    	NOTIFICATION - END 
    =========================== -->
    
    <!-- ==========================
    	RECENT BLOG POSTS - START 
    =========================== -->
    <section class="content recent-blog-posts">
        <div class="container">
        	<div class="section-title">
                <h2>Latest from blog</h2>
                <p>Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
            </div>
        	<div class="row">
            	
                <!-- BLOG POST - START -->
                <div class="col-xs-6 col-sm-3">
                    <article class="post">
                    	<img src="assets/images/blog/blog-1.jpg" class="img-responsive" alt="">
                        <h3><a href="single-post.phtml">How to pickup shoes</a></h3>
                        <span class="date">01/12/2015</span>
                    </article>
                </div>
                <!-- BLOG POST - END -->
                
                <!-- BLOG POST - START -->
                <div class="col-xs-6 col-sm-3">
                    <article class="post">
                    	<img src="assets/images/blog/blog-2.jpg" class="img-responsive" alt="">
                        <h3><a href="single-post.phtml">Fine mens gloves</a></h3>
                        <span class="date">24/11/2015</span>
                    </article>
                </div>
                <!-- BLOG POST - END -->
                
                <!-- BLOG POST - START -->
                <div class="col-xs-6 col-sm-3">
                    <article class="post">
                    	<img src="assets/images/blog/blog-3.jpg" class="img-responsive" alt="">
                        <h3><a href="single-post.phtml">Sunglasses for a beach</a></h3>
                        <span class="date">10/11/2015</span>
                    </article>
                </div>
                <!-- BLOG POST - END -->
                
                <!-- BLOG POST - START -->
                <div class="col-xs-6 col-sm-3">
                    <article class="post">
                    	<img src="assets/images/blog/blog-4.jpg" class="img-responsive" alt="">
                        <h3><a href="single-post.phtml">Pyjamas for a good night</a></h3>
                        <span class="date">19/10/2015</span>
                    </article>
                </div>
                <!-- BLOG POST - END -->
                
            </div>
        </div>
    </section>
     <!-- ==========================
    	RECENT BLOG POSTS - END 
    =========================== -->
    
    <!-- ==========================
    	BRANDS - START 
    =========================== -->
    <!--<section class="content brands pattern border-top border-bottom">
        <div class="container">
        	<div id="brands-carousel">
            	<div class="item"><a href="lookbook.phtml"><img src="assets/images/clients/1.png" class="img-responsive" alt=""></a></div>
                <div class="item"><a href="lookbook.phtml"><img src="assets/images/clients/2.png" class="img-responsive" alt=""></a></div>
                <div class="item"><a href="lookbook.phtml"><img src="assets/images/clients/3.png" class="img-responsive" alt=""></a></div>
                <div class="item"><a href="lookbook.phtml"><img src="assets/images/clients/4.png" class="img-responsive" alt=""></a></div>
                <div class="item"><a href="lookbook.phtml"><img src="assets/images/clients/5.png" class="img-responsive" alt=""></a></div>
                <div class="item"><a href="lookbook.phtml"><img src="assets/images/clients/6.png" class="img-responsive" alt=""></a></div>
                <div class="item"><a href="lookbook.phtml"><img src="assets/images/clients/7.png" class="img-responsive" alt=""></a></div>
            </div>
        </div>
    </section>-->
    <!-- ==========================
    	BRANDS - END 
    =========================== -->
        
    <!-- ==========================
    	SMALL PRODUCTS - START 
    =========================== -->
    <section class="content small-products">
        <div class="container">
        	<div class="row">
                <!-- COLUMN - START -->
                <div class="col-sm-4">
                    <h2>On Sale Products</h2>
                    <ul class="list-unstyled small-product">
                    	
               			<!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-1.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <span class="price">
                                <del><span class="amount">£36.00</span></del>
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-2.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <span class="price">
                                <del><span class="amount">£36.00</span></del>
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <span class="price">
                                <del><span class="amount">£36.00</span></del>
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                    </ul>
                </div>
                <!-- COLUMN - END -->
                
                <!-- COLUMN - START -->
                <div class="col-sm-4">
                    <h2>Featured Products</h2>
                    <ul class="list-unstyled small-product">
                    	
               			<!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-1.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <span class="price">
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-2.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <span class="price">
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <span class="price">
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                    </ul>
                </div>
                <!-- COLUMN - END -->
                
                <!-- COLUMN - START -->
                <div class="col-sm-4">
                    <h2>Top Rated Products</h2>
                    <ul class="list-unstyled small-product">
                    	
               			<!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-1.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-2.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                        <!-- PRODUCT - START -->
                        <li class="clearfix">
                        	<a href="singleProduct.phtml">
                            	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                            	<h3>Sunny Tank Selected Femme</h3>
                            </a>
                            <div class="product-rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="price">
                                <ins><span class="amount">£30.00</span></ins>
                            </span>
                        </li>
                        <!-- PRODUCT - END -->
                        
                    </ul>
                </div>
                <!-- COLUMN - END -->
                
            </div>
        </div>
    </section>
     <!-- ==========================
    	SMALL PRODUCTS - END 
    =========================== -->

    
    </div> <!-- PAGE - END -->

<?php }
}
?>