<?php
    include($_SERVER['DOCUMENT_ROOT'].'/sweeteaze/controllers/title.inc.php');
    require_once('controllers/config.inc.php');
    $currentPage = basename($_SERVER['SCRIPT_FILENAME']);

    ?>
<!DOCTYPE html>
<html>
<head>
    <!-- ==========================
    	Meta Tags 
    =========================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        

        <!-- ==========================
            JS - START 
        =========================== -->
            <?php include('controllers/html_dependencies_top.inc.php'); ?>
        <!-- ==========================
            NEWSLETTER - END 
        =========================== -->     
    
</head>
<body>
	
    <!-- ==========================
    	SCROLL TOP - START 
    =========================== -->
    <div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
    <!-- ==========================
    	SCROLL TOP - END 
    =========================== -->
    

    
    <div id="page-wrapper"> <!-- PAGE - START -->
    
	<!-- ==========================
    	HEADER - START 
    =========================== -->
        <?php include('controllers/header.inc.php'); ?>
    <!-- ==========================
    	HEADER - END 
    =========================== -->   
    
    <!-- ==========================
    	BREADCRUMB - START 
    =========================== -->
    <section class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <h2></h2>
                    <p></p>
                </div>
                <div class="col-xs-6">
                    <ol class="breadcrumb">
                        <li><a href="index.phtml">Home</a></li>
                        <li class="active">Privacy Policy</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
	<!-- ==========================
    	BREADCRUMB - END 
    =========================== -->
    
    <!-- ==========================
    	ESHOP - START 
    =========================== -->
    <section class="content eshop">
        <div class="container">
        	<div class="default-style privacy-policy">
        		<h2>Privacy Policy</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.</p>
                <p>Sed eget pulvinar quam, vel feugiat enim. Aliquam erat volutpat. Phasellus eu porta ipsum. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per. Vestibulum velmo.</p>
        	</div>
        </div>
    </section>
    <!-- ==========================
    	ESHOP - END 
    =========================== -->
       
    <!-- ==========================
    	NEWSLETTER - START 
    =========================== -->
    <?php include('controllers/newsletter.inc.php'); ?>
    <!-- ==========================
    	NEWSLETTER - END 
    =========================== -->
    
    <!-- ==========================
    	FOOTER - START 
    =========================== -->
    <?php include('controllers/footer.inc.php'); ?>
    <!-- ==========================
    	FOOTER - END 
    =========================== -->

    
    </div> <!-- PAGE - END -->

        <!-- ==========================
            JS - START 
        =========================== -->
            <?php include('controllers/html_dependencies_bottom.inc.php'); ?>
        <!-- ==========================
            NEWSLETTER - END 
        =========================== --> 
</body>
</html>