<?php
ob_start();
require_once('../includes/gen_access_timeout.inc.php');
 //require_once('../includes/session_timeout.inc.php'); this file here will be reserved only for highly secure (member-only) pages.
include('../includes/title.inc.php');
require_once('../includes/config.inc.php'); 
require('../includes/register.inc.php');
$currentPage = basename($_SERVER['SCRIPT_FILENAME']);

$econfirm = false;
$mailresult = false;
?>

<!DOCTYPE HTML>
<html class="no-js" lang="en-gb">  
<head>    
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<!--<meta name="viewport" content="width=device-width">-->    
<title><?php echo "Camerooncom-".$title; ?></title>
        
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>
    <!--<script src="js/videogallery_slider.js"></script>-->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
   <!--<script src="jquery-1.7.js" type="text/javascript"></script>
    <script src="jquery.tmpl.js" type="text/javascript"></script>-->
    <script src="jquery-ui-1.8.16.custom.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="styles.css"/>
    <link rel="stylesheet" type="text/css" href="css/jquery-ui-1.8.16.custom.css"/>
    
    <!--This style line below here fetches stylish font from google, thanks cHRIS mills-->
   <link href='http://fonts.googleapis.com/css?family=Lobster|Terminal+Dosis' rel='stylesheet' type='text/css'>
    
 <script type="text/javascript">				

function validate(form)
{
		if ($('#forgotstatus').val() == 'yes')
		{
			fail = validateEmail(form.forgot_pass_input.value);
			if (fail == "")
			{
				return true;
			}
			else
			{
				alert(fail);
				return false;
			}
		}
		else
		{ 
			fail = validateFirstname(form.firstname.value)
			fail += validateUsername(form.username.value)
			fail += validatePassword(form.pwd.value)
		
			if (fail == "") 
			{
				return true;
			}
			else 
			{ 
				alert(fail); 
				return false; 
			}
	} 
}   
			    
    </script>
        

<link rel="icon" href="../../favicon.ico">

<link rel="stylesheet" type="text/css" href="../css/random.css">

<link rel="stylesheet" type="text/css" href="../css/bootstrap.css">

<link rel="stylesheet" href="../css/normalize.min.css">
        
<link href="../css/superfish.css" rel="stylesheet" type="text/css" />        
              
        <style type= "text/css">
		
		article, aside, audio, canvas, datalist, details, figcaption, figure, footer, mark, header, hgroup, menu,
		nav, section, video { 
		
		display: block;
		}
		
		</style>
        
        <script src="../js/css3-mediaqueries.js"></script>
        
        <script src="../js/selectivizr.js"></script>

        <script src="../js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        
        <!--[if Lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
        </script>
        <![endif]-->
        

        
        
 <script src="../js/hoverIntent.js" type="text/javascript" charset="utf-8"></script>
 <script src="../js/superfish.js" type="text/javascript" charset="utf-8"></script>
        
 <script type="text/javascript">
$(function() {
	$('ul.sf-menu').superfish({
		autoArrows: true,
		speed: 'fast'
	});
});

</script>
     

<!--[if lt IE 9]>      
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js">       
</script>     

<![endif]-->   

</head>  

<body>
<section id="mainwrapper" class="container"> <!--THIS CONTAINER CLASS SHOULD INVOKE BOOTSTRAP-->

<section id="headerforviews">


<?php include_once($_SERVER['DOCUMENT_ROOT'] . "/camerooncom/includes/header.inc.php"); ?>

</section><!--END OF HEADER SECTION (CONTAINER)-->


<section id="main_content">

<article id="sidebar">
<?php
//Let's include the sidebar here
 include("../includes/camcomsidebar.inc.php");
?>
</article>

<article id="floatbg" style="background-color: #FFF;">

<div class="jumbotron">
<div class="well">
<!--<table class="signup" class="table" cellpadding="5"
	cellspacing="5">-->
<h2><?php if (($econfirm) && ($econfirm == "true")) { echo RegisLoginTransGarrison::accountActivationMsg(); } else { ?><p style="color: #069; font-weight: bold;"><?php echo RegisloginTransGarrison::requestToRegister(); ?></p> <?php } ?></h2>

<p><?php echo RegisLoginTransGarrison::requestToLogin(); ?></p>

<?php if ($fail) { echo "<p>".RegisLoginTransGarrison::regisErrorAnnounce()."</p> <p><font color=red size=3><br /><i>$fail</i></font></p>"; } elseif (isset($success)) { echo "$success"; } ?>



</div><!--END OF THE JUMBOTRON's WELL-->



    
    <form id="regis_form" method="post" action=""
	onSubmit="return validate(this)"><!--THIS IS WHERE THE JS FUNCTIONS ARE CALLED WHEN THE FORM IS SUBMITTED. You put it inside the opening <form> tag, its a listening function 'onSubmit', but then u use it as an attribute with = symbols, and obviously the action to be akem in quotes. validate(this) where validateform() is the function to be run, while this refers to the current object(form).-->
     

<div id="regis_panel" class="panel panel-primary">

    <div class="panel-heading">

        <h3 class="panel-title">REGISTER</h3>

    </div>

    <div class="panel-body">

     <p>First name</p><input type="text" class="regisforminput" placeholder="first name" maxlength="32"
	name="firstname" id="firstname" value="<?php if ($fail) { echo $firstname;} else { echo ''; } ?>" />
	<hr />
    
    <p>Surname</p><input type="text" class="regisforminput" placeholder="surname" maxlength="32"
	name="surname" value="<?php if ($fail) { echo $surname;} else { echo ''; }?>" />
    <hr />
    
    <p>Username</p><input type="text" class="regisforminput" placeholder="username" maxlength="20"
	name="username" <?php if (($fail) || ($errors)) { echo 'value="' . htmlentities($username, ENT_COMPAT, 'UTF-8') . '"'; } ?> onBlur='checkUsername(this)' /><span id='info'></span><br />
	<hr />
    <p>Password</p><input type="password" class="regisforminput" placeholder="password" maxlength="12"
    name="pwd" /></td><!--For the password field we dont redisplay the value of e entered pw if there are errors. The "password" value of the 'type' attribute makes the form field hide the entered values-->
    <hr />
    
     <p>Confirm Your Password</p><input type="password" class="regisforminput" 
     maxlength="12" name="conf_pwd" placeholder="confirm password" id="conf_pwd" required>
  	<hr />
    
    <p>Age</p><input type="text" class="regisforminput" maxlength="3"
	name="age" placeholder="age" value="<?php if ($fail) { echo $age;} else { echo ''; }?>" />
	<hr />
    
    <p>Phone number</p><input type="text" class="regisforminput" maxlength="16"
	name="phone" placeholder="phone number" value="<?php if ($fail) { echo $phone;} else { echo ''; }?>" />
	<hr />
    
    <p>Email</p><input type="text" class="regisforminput" maxlength="64"
	name="email" placeholder="email" required value="<?php if ($fail) { echo $email;} else { echo ''; }?>" />
	</div><!--END OF BODY OF PANEL HOLDING REGIS FORM-->
    
    <div class="panel-footer clearfix">

        	<div class="pull-right">

            	<input type="submit" name="signup_to_camcom" class="btn btn-primary" value="Register" />

        	</div><!--end of div holding form button(s)-->

    </div><!--end of panel footer-->        
    </div><!--END OF PANEL-->
        
    </form>
</div><!--END OF THE JUMBOTRON-->

<div class="clearer"></div><!--THIS IS THE LAST <DIV> (THING) INSIDE THIS FLOATBG CONTAINER COZ IT KEEPS EVERYTHING ABOVE IT-->

</article>

</section><!--END OF MAINCONTENT THAT CONTAINS THE SIDEBAR, N THE FLOATBG-->





<section class="first_footer">
	<div class="well">
      		<?php include_once($_SERVER['DOCUMENT_ROOT'] . "/camerooncom/includes/first_footer.inc.php"); //include the 1st footer here ?>           
	        <div class="clearer" id="firstfooterdivclear"></div><!--NOTE THAT THIS IS THE LAST DIV (THING) INSIDE the well of THE first_footer-->
    </div><!--END OF THE WELL DIV INSIDE THE first_footer SECTION-->  
</section><!--End of first footer csection--> 
  

<article id="footer"><!--HERE'S THE START OF THE SECOND FOOTER; IT'S ENCLOSED IN THIS PAIR OF <article></article> tags ided 		
					'footer'-->
			<?php include_once($_SERVER['DOCUMENT_ROOT'] . "/camerooncom/includes/footer.inc.php"); //include the 2nd footer here ?> 
			<div class="clearer"></div><!--to make this empty div work n keep everything before it above it; that's why it's the last 	
            			thing (div) inside the second-footer part of the website (enclosed in a pair of <article tags>. You also need 
                        to make sure the footer element has no height rule-->   
</article>

                            


        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.1.min.js"><\/script>')</script>

        <script src="js/main.js"></script>
        
   
        
    <!--STYLES N SCRIPTS FOR THE FINAL 'OUR SERVICES' TAB, i had to mix it with that of the slider code, as well as leave the same <script> tags for the jq tabs at the top of this page for some reason bf it would work-->
    <script src="js/jquery-1.7.js" type="text/javascript"></script>
    
     <script src="js/sliderengine/jquery.js"></script>
     
    <script src="js/jquery.tmpl.js" type="text/javascript"></script>
    <script src="js/jquery-ui-1.8.16.custom.js" type="text/javascript"></script>
    
    <script src="js/sliderengine/amazingslider.js"></script>
    
    <link rel="stylesheet" type="text/css" href="css/styles.css"/>
    <link rel="stylesheet" type="text/css" href="js/jquery-ui-1.8.16.custom.css"/>

    <script src="js/sliderengine/initslider-1.js"></script> 


</section><!--END OF THE MAINWRAPPER SECTION THAT CONTAINS EVERYTHING-->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <!--<script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>-->
    <script src="../js/bootstrap.js"></script>
    <script src="../js/docs.min.js"></script>

    
   	<script type="text/javascript">
	  
 	</script>
    
      
</body>
</html>

