<?php
namespace layouts\reserveViewTemplates;


class signup extends \DGZ_library\DGZ_HtmlView
{


function show()
{ ?>

        <div id="page-wrapper"> <!-- PAGE - START -->

        <!-- ==========================
            BREADCRUMB - START 
        =========================== -->
        <section class="breadcrumb-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-xs-6">
                    </div>
                    <div class="col-xs-6">
                        <ol class="breadcrumb">
                            <li><a href="index.phtml">Home</a></li>
                            <li class="active">Sign Up</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
            <!-- ==========================
            BREADCRUMB - END 
        =========================== -->

        <!-- ==========================
            ACCOUNT - START 
        =========================== -->
        <section class="content account">
            <div class="container">
                    <div class="row">
                    <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
                            <div class="login-form-wrapper">

                            <form id="regis_form" method="post" action="" onSubmit="">
                                    <h3>Sign Up</h3>
                                <div class="form-group">
                                    <label for="firstname">First name<span class="required">*</span></label>
                                    <input type="text" class="form-control" class="regisforminput" placeholder="first name" maxlength="32"
                                        name="firstname" id="firstname" />
                                </div>
                                <div class="form-group">
                                    <label for="surname">Last name<span class="required">*</span></label>
                                    <input type="text" class="form-control" class="regisforminput" placeholder="surname" maxlength="32"
                                        name="surname" id="surname" />
                                </div>
                                <div class="form-group">
                                    <label for="email">Email<span class="required">*</span></label>
                                    <input type="email" class="form-control regisforminput" maxlength="64"
                                        name="email" id="email" placeholder="email" required />
                                </div>
                                <div class="form-group">
                                    <label>Password<span class="required">*</span></label>
                                    <input type="password" class="form-control regisforminput" placeholder="password" maxlength="12" name="pwd" id="pwd" />
                                </div>
                                <div class="form-group">
                                    <label>Confirm your Password<span class="required">*</span></label>
                                    <input type="password" maxlength="12" name="conf_pwd" placeholder="confirm password" id="conf_pwd"  class="form-control regisforminput" />
                                </div>    
                                <button type="submit" name="signup_to_sweeteaze"  class="btn btn-primary btn-lg btn-block">Register</button>
                            </form>
                            <!--<div class="row">
                                <div class="col-xs-6">
                                    <a href="" class="btn btn-brand btn-facebook"><i class="fa fa-facebook"></i>Sign up with Facebook</a>
                                </div>
                                <div class="col-xs-6">
                                    <a href="" class="btn btn-brand btn-google-plus"><i class="fa fa-google-plus"></i>Sign up with Google Plus</a>
                                </div>
                            </div>-->
                        </div>
                        <p class="form-text">Already have an account? <a href="signin.phtml">Log in</a></p>
                    </div>
                </div>
            </div>
        </section>
        <!-- ==========================
            ACCOUNT - END 
        =========================== -->

        </div> <!-- PAGE - END -->

<?php }
}
?>