<?php
namespace layouts\reserveViewTemplates;


class signin extends \DGZ_library\DGZ_HtmlView
{


function show()
{ ?>
	
    <!-- ==========================
    	SCROLL TOP - START 
    =========================== -->
    <div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
    <!-- ==========================
    	SCROLL TOP - END 
    =========================== -->
    

    
    <div id="page-wrapper"> <!-- PAGE - START -->

    
    <!-- ==========================
    	BREADCRUMB - START 
    =========================== -->
    <section class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                </div>
                <div class="col-xs-6">
                    <ol class="breadcrumb">
                        <li><a href="index.phtml">Home</a></li>
                        <li class="active">Sign In</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
	<!-- ==========================
    	BREADCRUMB - END 
    =========================== -->
    
    <!-- ==========================
    	ACCOUNT - START 
    =========================== -->
    <section class="content account">
        <div class="container">
        	<div class="row">
            	<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
                    
                	<div class="login-form-wrapper">
                        <form id="loginform" method="post" action="">
                        	<h3>Sign In</h3>
                            <div class="form-group">
                                <label for="email" class="loginfieldinput" >Email<span class="required">*</span></label>
                                <input type="email" maxlength="50" id="email" name="email" placeholder="email"  class="form-control loginfieldinput">
                            </div>
                            <div class="form-group">
                                <label for="pwd" class="loginfieldinput" >Password<span class="required">*</span></label>
                                <input type="password" class="form-control loginfieldinput" maxlength="20" placeholder="password" name="pwd" id="pwd" />
                            </div>
                            <div class="form-group">
                                <input type="button" id="forgot_pass" name="forgot_pass" value="Forgot your password?" />
                                <br />
                                <input type="email" maxlength="40" class="form-control loginfieldinput" id="forgot_pass_input" name="forgot_pass_input" placeholder="Email address here" style="display: none; margin-top: 5px;" /><span style="display: none; margin-top: 5px;" class="loginfieldinput" id="forgot_pass_info">&nbsp;&larr;<font color=blue>Enter your email address to receive your password</font></span>
                            </div>        
                                <input id="forgotstatus" type="hidden" name="forgotstatus" value="no" />     
                            <div class="checkbox form-group">
                            <!--<div class="checkbox">-->
                                <input type="checkbox" id="signin-remember" name="rem_me">
                                <label for="signin-remember" class="loginfieldinput">Remember me-<small>Not recommended on a shared computer</small></label>
                            <!--</div>-->
                            </div>
                            <button type="submit" id="login" name="login" class="btn btn-primary btn-lg btn-block">Login</button>
                        </form>
                            
             
                            
                        <div class="row">
                            <div class="col-xs-6">
                                <a href="" class="btn btn-brand btn-facebook"><i class="fa fa-facebook"></i>Sign in with Facebook</a>
                            </div>
                            <div class="col-xs-6">
                                <a href="" class="btn btn-brand btn-google-plus"><i class="fa fa-google-plus"></i>Sign in with Google Plus</a>
                            </div>
                        </div>
                    </div>
                    <p class="form-text">Did you <a href="lostPassword.phtml">forget your password?</a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- ==========================
    	ACCOUNT - END 
    =========================== -->

    
    </div> <!-- PAGE - END -->

<?php }
}
?>