<?php
namespace layouts\reserveViewTemplates;


class stores extends \DGZ_library\DGZ_HtmlView
{


    function show()
    { ?>
	
    <!-- ==========================
    	SCROLL TOP - START 
    =========================== -->
    <div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
    <!-- ==========================
    	SCROLL TOP - END 
    =========================== -->
    
	<!-- ==========================
    	COLOR SWITCHER - START 
    =========================== -->
	<div id="color-switcher">
        <div id="toggle-switcher"><i class="fa fa-gear"></i></div>
        <span>Color Scheme:</span>
        <ul class="list-unstyled list-inline">
            <li id="red" data-toggle="tooltip" data-placement="top" title="" data-original-title="Red"></li>
            <li id="purple" data-toggle="tooltip" data-placement="top" title="" data-original-title="Purple"></li>
            <li id="yellow" data-toggle="tooltip" data-placement="top" title="" data-original-title="Yellow"></li>
            <li id="blue" data-toggle="tooltip" data-placement="top" title="" data-original-title="Blue"></li>
            <li id="dark-blue" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dark Blue"></li>
            <li id="orange" data-toggle="tooltip" data-placement="top" title="" data-original-title="Orange"></li>
            <li id="green" data-toggle="tooltip" data-placement="top" title="" data-original-title="Green"></li>
            <li id="brown" data-toggle="tooltip" data-placement="top" title="" data-original-title="Brown"></li>
            <li id="dark-red" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dark Red"></li>
            <li id="light-green" data-toggle="tooltip" data-placement="top" title="" data-original-title="Light Green"></li>
        </ul>
    </div>
	<!-- ==========================
    	COLOR SWITCHER - END 
    =========================== -->
    
    <div id="page-wrapper"> <!-- PAGE - START -->
    
	<!-- ==========================
    	HEADER - START 
    =========================== -->
	<div class="top-header hidden-xs">
    	<div class="container">
            <div class="row">
                <div class="col-sm-5">
                    <ul class="list-inline contacts">
                        <li><i class="fa fa-envelope"></i> help@dorguzen.com</li>
                        <li><i class="fa fa-phone"></i> 754 213 456</li>
                    </ul>
                </div>
                <div class="col-sm-7 text-right">
                    <ul class="list-inline links">
                        <li><a href="my-account.html">My account</a></li>
                        <li><a href="checkout.html">Checkout</a></li>
                        <li><a href="wishlist.html">Wishlist (5)</a></li>
                        <li><a href="compare.html">Compare (3)</a></li>
                        <li><a href="signin.html">Logout</a></li>
                    </ul>
                    <ul class="list-inline languages hidden-sm">
                    	<li><a href="#"><img src="assets/images/flags/cz.png" alt="cs_CZ"></a></li>
                        <li><a href="#"><img src="assets/images/flags/us.png" alt="en_US"></a></li>
                        <li><a href="#"><img src="assets/images/flags/de.png" alt="de_DE"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <header class="navbar navbar-default navbar-static-top">
    	<div class="container">
            <div class="navbar-header">
                <a href="index.html" class="navbar-brand"><span>DOR</span>GUZEN</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></button>
            </div>
            <div class="navbar-collapse collapse">
            	<p class="navbar-text hidden-xs hidden-sm">The easiest way to shop</p>
            	<ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Home</a>
                      	<ul class="dropdown-menu">
                        	<li><a href="index.html">Homepage 1</a></li>
                            <li><a href="homepage-2.html">Homepage 2</a></li>
                            <li><a href="homepage-3.html">Homepage 3<span class="label label-warning pull-right">Updated</span></a></li>
                            <li><a href="homepage-4.html">Homepage 4</a></li>
                            <li><a href="homepage-5.html">Homepage 5<span class="label label-danger pull-right">New</span></a></li>
                            <li><a href="homepage-6.html">Homepage 6<span class="label label-danger pull-right">New</span></a></li>
                      	</ul>
                    </li>
                    <li class="dropdown megamenu">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Eshop</a>
                      	<ul class="dropdown-menu">
                            <li class="col-sm-4 col-md-3">
                            	<ul class="list-unstyled">
                                	<li class="title">Men <span class="label label-danger pull-right">HOT</span></li>
                                    <li><a href="products.html">Sweatshirts & Jackets</a></li>
                                    <li><a href="products.html">Caps and Hats</a></li>
                                    <li><a href="products.html">Ties</a></li>
                                    <li><a href="products.html">Scarves</a></li>
                                    <li><a href="products.html">Shirts</a></li>
                                    <li><a href="products.html">Jeans</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4 col-md-3">
                            	<ul class="list-unstyled">
                                	<li class="title">Women <span class="label label-info pull-right">30% OFF SALE</span></li>
                                    <li><a href="products.html">Jackets & Coats</a></li>
                                    <li><a href="products.html">Jumpers & cardigans</a></li>
                                    <li><a href="products.html">Jeans</a></li>
                                    <li><a href="products.html">Trousers</a></li>
                                    <li><a href="products.html">Dresses</a></li>
                                    <li><a href="products.html">Long Sleeve Tops</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4 col-md-3">
                            	<ul class="list-unstyled">
                                	<li class="title">Accessories</li>
                                    <li><a href="products.html">Sunglasses</a></li>
                                    <li><a href="products.html">Watches</a></li>
                                    <li><a href="products.html">Umbrellas</a></li>
                                    <li><a href="products.html">Bags & Wallets</a></li>
                                    <li><a href="products.html">Fashion Jewellery</a></li>
                                    <li><a href="products.html">Belts</a></li>
                                </ul>
                            </li>
                            <li class="hidden-xs hidden-sm col-md-3">
                            	<img src="assets/images/megamenu.png" class="img-responsive center-block" alt="">
                            </li>
                      	</ul>
                    </li>
                    <li class="dropdown megamenu">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Pages</a>
                      	<ul class="dropdown-menu">
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                	<li class="title">Eshop</li>
                                    <li><a href="products.html">Products</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="compare.html">Compare</a></li>
                                    <li><a href="single-product.html">One Product</a></li>
                                    <li><a href="stores.html">Stores</a></li>
                                    <li><a href="about-shop.html">About Shop</a></li>
                                    <li><a href="lookbook.html">Lookbook</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                	<li class="title">Account</li>
                                    <li><a href="my-account.html">My Account<span class="label label-warning pull-right">Updated</span></a></li>
                                    <li><a href="profile.html">Profile</a></li>
                                    <li><a href="orders.html">Ordres</a></li>
                                    <li><a href="wishlist.html">Wishlist</a></li>
                                    <li><a href="address.html">Address</a></li>
                                    <li><a href="warranty-claims.html">Warranty Claims<span class="label label-danger pull-right">New</span></a></li>
                                    <li><a href="signup.html">Sign Up</a></li>
                                    <li><a href="signin.html">Sign In</a></li>
                                    <li><a href="lost-password.html">Lost Password</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                	<li class="title">Other Pages</li>
                                    <li><a href="blog.html">Blog</a></li>
                                    <li><a href="single-post.html">One Blog Post</a></li>
                                    <li><a href="single-order.html">Order Detail</a></li>
                                    <li><a href="downloads.html">Downloads<span class="label label-danger pull-right">New</span></a></li>
                                    <li><a href="faq.html">FAQ</a></li>
                                    <li><a href="privacy-policy.html">Privacy Policy</a></li>
                                    <li><a href="terms-conditions.html">Terms & Conditions</a></li>
                                    <li><a href="404.html">404 Error</a></li>
                                    <li><a href="email-template.html" target="_blank">Email Template</a></li>
                                </ul>
                            </li>
                      	</ul>
                    </li>
                    <li class="dropdown megamenu">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true">Components<span class="label label-danger pull-right">New</span></a>
                      	<ul class="dropdown-menu">
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                    <li><a href="components.html#headings">Headings</a></li>
                                    <li><a href="components.html#paragraphs">Paragraphs</a></li>
                                    <li><a href="components.html#lists">Lists</a></li>
                                    <li><a href="components.html#tabs">Tabs</a></li>
                                    <li><a href="components.html#accordition">Accordition</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                    <li><a href="components.html#collapse">Collapse</a></li>
                                    <li><a href="components.html#buttons">Buttons</a></li>
                                    <li><a href="components.html#tables">Tables</a></li>
                                    <li><a href="components.html#grids">Grids</a></li>
                                    <li><a href="components.html#responsive-video-audio">Responsive Video &amp; Audio</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-4">
                            	<ul class="list-unstyled">
                                    <li><a href="components.html#alerts">Alerts</a></li>
                                    <li><a href="components.html#forms">Forms</a></li>
                                    <li><a href="components.html#labels">Labels</a></li>
                                    <li><a href="components.html#paginations">Paginations</a></li>
                                    <li><a href="components.html#carousels">Carousels</a></li>
                                </ul>
                            </li>
                      	</ul>
                    </li>
                    <li class="dropdown navbar-cart hidden-xs">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true"><i class="fa fa-shopping-cart"></i></a>
                      	<ul class="dropdown-menu">
                        	
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-3">
                                    	<img src="assets/images/products/product-1.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-9">
                                    	<h4><a href="single-product.html">Fusce Aliquam</a></h4>
                                        <p>1x - $20.00</p>
                                    	<a href="#" class="remove"><i class="fa fa-times-circle"></i></a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-3">
                                    	<img src="assets/images/products/product-2.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-9">
                                    	<h4><a href="single-product.html">Fusce Aliquam</a></h4>
                                        <p>1x - $20.00</p>
                                    	<a href="#" class="remove"><i class="fa fa-times-circle"></i></a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-3">
                                    	<img src="assets/images/products/product-3.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-9">
                                    	<h4><a href="single-product.html">Fusce Aliquam</a></h4>
                                        <p>1x - $20.00</p>
                                    	<a href="#" class="remove"><i class="fa fa-times-circle"></i></a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                            <!-- CART ITEM - START -->
                            <li>
                            	<div class="row">
                                	<div class="col-sm-6">
                                    	<a href="cart.html" class="btn btn-primary btn-block">View Cart</a>
                                    </div>
                                    <div class="col-sm-6">
                                    	<a href="checkout.html" class="btn btn-primary btn-block">Checkout</a>
                                    </div>
                                </div>
                            </li>
                            <!-- CART ITEM - END -->
                            
                      	</ul>
                    </li>
                    <li class="dropdown navbar-search hidden-xs">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
                      	<ul class="dropdown-menu">
                        	<li>
                                <form>
                                    <div class="input-group input-group-lg">
                                        <input type="text" class="form-control" placeholder="Search ...">
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary" type="button">Search</button>
                                        </span>
                                    </div>
                                </form>
                            </li>
                      	</ul>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <!-- ==========================
    	HEADER - END 
    =========================== --> 
    
    <!-- ==========================
    	BREADCRUMB - START 
    =========================== -->
    <section class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <h2>Dorguzen</h2>
                    <p>Our Stores</p>
                </div>
                <div class="col-xs-6">
                    <ol class="breadcrumb">
                        <li><a href="index.html">Home</a></li>
                        <li class="active">Our Stores</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
	<!-- ==========================
    	BREADCRUMB - END 
    =========================== -->
    
    <div class="map-wrapper">
        <div id="map-canvas"></div>
        <div id="map-tooltip"></div>
    </div>
    
    <!-- ==========================
    	ESHOP - START 
    =========================== -->
    <section class="content eshop">
        <div class="container">
            <div class="stores">
                
                <div class="row">
                    <div class="col-sm-7">
                        <h2>Let's check our Stores</h2>
                    </div>
                    <div class="col-sm-5">
                        <form class="form-inline">
                            <div class="form-group">
                                <label for="change-region">Select city:</label>
                                <select class="form-control"  id="change-region">
                                    <option value="1" selected>Prague</option>
                                    <option value="2">New York</option>
                                    <option value="3">Berlin</option>
                                    <option value="4">Paris</option>
                                </select>
                            </div>
                        </form>
                    </div>
                </div>
                    
                <div id="test"></div>    
                            
                <div class="tabs" id="tabs-regions">
                    <ul class="nav nav-tabs hidden" role="tablist">
                        <li role="presentation" class="active"><a href="#region-1" role="tab" data-toggle="tab" aria-controls="region-1" aria-expanded="false">Prague</a></li>
                        <li role="presentation" class=""><a href="#region-2" role="tab" data-toggle="tab" aria-controls="region-2" aria-expanded="true">New York</a></li>
                        <li role="presentation" class=""><a href="#region-3" role="tab" data-toggle="tab" aria-controls="region-3" aria-expanded="true">Berlin</a></li>
                        <li role="presentation" class=""><a href="#region-4" role="tab" data-toggle="tab" aria-controls="region-4" aria-expanded="true">Paris</a></li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active in" id="region-1">
                            
                            <!-- STORE - START -->
                            <div class="default-style store row row-no-padding" id="marker-1">
                    			<div class="col-sm-7">
                            		<div class="store-body">
                            			<h3>Krakovská 1307/22, 110 00 Prague 1</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                                        <div class="row">
                                            <ul class="list-unstyled col-sm-6">
                                                <li><i class="fa fa-user"></i> <b>John Doe</b></li>
                                                <li><i class="fa fa-envelope"></i> <b>krakovska-prague@umarket.com</b></li>
                                                <li><i class="fa fa-phone"></i> <b>+420 754 213 456</b></li>
                                            </ul>
                                            <ul class="list-unstyled grey-color col-sm-6">
                                                <li><i class="fa fa-credit-card"></i> Credit Card payment</li>
                                                <li><i class="fa fa-calendar"></i> Installment payments</li>
                                            </ul>
                                        </div>
                            		</div>
                            	</div>
                                <div class="col-sm-5">
                                	<div class="store-image">
                                		<img src="assets/images/store-1.jpg" class="img-responsive" alt="">
                                        <div class="store-opening-hours">
                                        	<ul class="list-unstyled">
                                                <li><span>Mon</span> 8:00 - 20:00</li>
                                                <li><span>Tue</span> 8:00 - 20:00</li>
                                                <li><span>Wed</span> 12:00 - 20:00</li>
                                                <li><span>Thu</span> 12:00 - 20:00</li>
                                                <li><span>Fri, Sat, Sun</span> Closed</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- STORE - END -->
                            
                            <!-- STORE - START -->
                            <div class="default-style store row row-no-padding" id="marker-2">
                    			<div class="col-sm-7">
                            		<div class="store-body">
                            			<h3>Vězeňská 910/2, 110 00 Prague 1-Staré Město</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                                        <div class="row">
                                            <ul class="list-unstyled col-sm-6">
                                                <li><i class="fa fa-user"></i> <b>John Doe</b></li>
                                                <li><i class="fa fa-envelope"></i> <b>krakovska-prague@umarket.com</b></li>
                                                <li><i class="fa fa-phone"></i> <b>+420 754 213 456</b></li>
                                            </ul>
                                            <ul class="list-unstyled grey-color col-sm-6">
                                                <li><i class="fa fa-credit-card"></i> Credit Card payment</li>
                                                <li><i class="fa fa-calendar"></i> Installment payments</li>
                                            </ul>
                                        </div>
                            		</div>
                            	</div>
                                <div class="col-sm-5">
                                	<div class="store-image">
                                		<img src="assets/images/store-2.jpg" class="img-responsive" alt="">
                                        <div class="store-opening-hours">
                                        	<ul class="list-unstyled">
                                                <li><span>Mon</span> 8:00 - 20:00</li>
                                                <li><span>Tue</span> 8:00 - 20:00</li>
                                                <li><span>Wed</span> 12:00 - 20:00</li>
                                                <li><span>Thu</span> 12:00 - 20:00</li>
                                                <li><span>Fri, Sat, Sun</span> Closed</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- STORE - END -->
                            
                            <!-- STORE - START -->
                            <div class="default-style store row row-no-padding" id="marker-3">
                    			<div class="col-sm-7">
                            		<div class="store-body">
                            			<h3>Na Hřebenkách 2, 150 00 Prague 5</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                                        <div class="row">
                                            <ul class="list-unstyled col-sm-6">
                                                <li><i class="fa fa-user"></i> <b>John Doe</b></li>
                                                <li><i class="fa fa-envelope"></i> <b>krakovska-prague@umarket.com</b></li>
                                                <li><i class="fa fa-phone"></i> <b>+420 754 213 456</b></li>
                                            </ul>
                                            <ul class="list-unstyled grey-color col-sm-6">
                                                <li><i class="fa fa-credit-card"></i> Credit Card payment</li>
                                                <li><i class="fa fa-calendar"></i> Installment payments</li>
                                            </ul>
                                        </div>
                            		</div>
                            	</div>
                                <div class="col-sm-5">
                                	<div class="store-image">
                                		<img src="assets/images/store-3.jpg" class="img-responsive" alt="">
                                        <div class="store-opening-hours">
                                        	<ul class="list-unstyled">
                                                <li><span>Mon</span> 8:00 - 20:00</li>
                                                <li><span>Tue</span> 8:00 - 20:00</li>
                                                <li><span>Wed</span> 12:00 - 20:00</li>
                                                <li><span>Thu</span> 12:00 - 20:00</li>
                                                <li><span>Fri, Sat, Sun</span> Closed</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- STORE - END -->
                            
                        </div>
                        <div role="tabpanel" class="tab-pane" id="region-2">
                            
                            <!-- STORE - START -->
                            <div class="default-style store row row-no-padding" id="marker-4">
                    			<div class="col-sm-7">
                            		<div class="store-body">
                            			<h3>63 Crosby St, New York, NY 10012</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                                        <div class="row">
                                            <ul class="list-unstyled col-sm-6">
                                                <li><i class="fa fa-user"></i> <b>John Doe</b></li>
                                                <li><i class="fa fa-envelope"></i> <b>store@umarket.com</b></li>
                                                <li><i class="fa fa-phone"></i> <b>+420 754 213 456</b></li>
                                            </ul>
                                            <ul class="list-unstyled grey-color col-sm-6">
                                                <li><i class="fa fa-credit-card"></i> Credit Card payment</li>
                                                <li><i class="fa fa-calendar"></i> Installment payments</li>
                                            </ul>
                                        </div>
                            		</div>
                            	</div>
                                <div class="col-sm-5">
                                	<div class="store-image">
                                		<img src="assets/images/store-4.jpg" class="img-responsive" alt="">
                                        <div class="store-opening-hours">
                                        	<ul class="list-unstyled">
                                                <li><span>Mon</span> 8:00 - 20:00</li>
                                                <li><span>Tue</span> 8:00 - 20:00</li>
                                                <li><span>Wed</span> 12:00 - 20:00</li>
                                                <li><span>Thu</span> 12:00 - 20:00</li>
                                                <li><span>Fri, Sat, Sun</span> Closed</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- STORE - END -->
                            
                        </div>
                        <div role="tabpanel" class="tab-pane" id="region-3">
                            
                            <!-- STORE - START -->
                            <div class="default-style store row row-no-padding" id="marker-5">
                    			<div class="col-sm-7">
                            		<div class="store-body">
                            			<h3>Bebelpl. 1, 10117 Berlin</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                                        <div class="row">
                                            <ul class="list-unstyled col-sm-6">
                                                <li><i class="fa fa-user"></i> <b>John Doe</b></li>
                                                <li><i class="fa fa-envelope"></i> <b>store@umarket.com</b></li>
                                                <li><i class="fa fa-phone"></i> <b>+420 754 213 456</b></li>
                                            </ul>
                                            <ul class="list-unstyled grey-color col-sm-6">
                                                <li><i class="fa fa-credit-card"></i> Credit Card payment</li>
                                                <li><i class="fa fa-calendar"></i> Installment payments</li>
                                            </ul>
                                        </div>
                            		</div>
                            	</div>
                                <div class="col-sm-5">
                                	<div class="store-image">
                                		<img src="assets/images/store-5.jpg" class="img-responsive" alt="">
                                        <div class="store-opening-hours">
                                        	<ul class="list-unstyled">
                                                <li><span>Mon</span> 8:00 - 20:00</li>
                                                <li><span>Tue</span> 8:00 - 20:00</li>
                                                <li><span>Wed</span> 12:00 - 20:00</li>
                                                <li><span>Thu</span> 12:00 - 20:00</li>
                                                <li><span>Fri, Sat, Sun</span> Closed</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- STORE - END -->
                            
                            <!-- STORE - START -->
                            <div class="default-style store row row-no-padding" id="marker-6">
                    			<div class="col-sm-7">
                            		<div class="store-body">
                            			<h3>Jablonskistraße 16, 10405 Berlin</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                                        <div class="row">
                                            <ul class="list-unstyled col-sm-6">
                                                <li><i class="fa fa-user"></i> <b>John Doe</b></li>
                                                <li><i class="fa fa-envelope"></i> <b>store@umarket.com</b></li>
                                                <li><i class="fa fa-phone"></i> <b>+420 754 213 456</b></li>
                                            </ul>
                                            <ul class="list-unstyled grey-color col-sm-6">
                                                <li><i class="fa fa-credit-card"></i> Credit Card payment</li>
                                                <li><i class="fa fa-calendar"></i> Installment payments</li>
                                            </ul>
                                        </div>
                            		</div>
                            	</div>
                                <div class="col-sm-5">
                                	<div class="store-image">
                                		<img src="assets/images/store-1.jpg" class="img-responsive" alt="">
                                        <div class="store-opening-hours">
                                        	<ul class="list-unstyled">
                                                <li><span>Mon</span> 8:00 - 20:00</li>
                                                <li><span>Tue</span> 8:00 - 20:00</li>
                                                <li><span>Wed</span> 12:00 - 20:00</li>
                                                <li><span>Thu</span> 12:00 - 20:00</li>
                                                <li><span>Fri, Sat, Sun</span> Closed</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- STORE - END -->
                            
                            <!-- STORE - START -->
                            <div class="default-style store row row-no-padding" id="marker-7">
                    			<div class="col-sm-7">
                            		<div class="store-body">
                            			<h3>Rigaer Str. 9, 10247 Berlin</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                                        <div class="row">
                                            <ul class="list-unstyled col-sm-6">
                                                <li><i class="fa fa-user"></i> <b>John Doe</b></li>
                                                <li><i class="fa fa-envelope"></i> <b>store@umarket.com</b></li>
                                                <li><i class="fa fa-phone"></i> <b>+420 754 213 456</b></li>
                                            </ul>
                                            <ul class="list-unstyled grey-color col-sm-6">
                                                <li><i class="fa fa-credit-card"></i> Credit Card payment</li>
                                                <li><i class="fa fa-calendar"></i> Installment payments</li>
                                            </ul>
                                        </div>
                            		</div>
                            	</div>
                                <div class="col-sm-5">
                                	<div class="store-image">
                                		<img src="assets/images/store-2.jpg" class="img-responsive" alt="">
                                        <div class="store-opening-hours">
                                        	<ul class="list-unstyled">
                                                <li><span>Mon</span> 8:00 - 20:00</li>
                                                <li><span>Tue</span> 8:00 - 20:00</li>
                                                <li><span>Wed</span> 12:00 - 20:00</li>
                                                <li><span>Thu</span> 12:00 - 20:00</li>
                                                <li><span>Fri, Sat, Sun</span> Closed</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- STORE - END -->
                            
                        </div>
                        <div role="tabpanel" class="tab-pane" id="region-4">
                            
                            <!-- STORE - START -->
                            <div class="default-style store row row-no-padding" id="marker-8">
                    			<div class="col-sm-7">
                            		<div class="store-body">
                            			<h3>18 Rue Antin, 75002 Paris</h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut feugiat mauris eget magna egestas porta. Curabitur sagittis sagittis neque rutrum congue.</p>
                                        <div class="row">
                                            <ul class="list-unstyled col-sm-6">
                                                <li><i class="fa fa-user"></i> <b>John Doe</b></li>
                                                <li><i class="fa fa-envelope"></i> <b>store@umarket.com</b></li>
                                                <li><i class="fa fa-phone"></i> <b>+420 754 213 456</b></li>
                                            </ul>
                                            <ul class="list-unstyled grey-color col-sm-6">
                                                <li><i class="fa fa-credit-card"></i> Credit Card payment</li>
                                                <li><i class="fa fa-calendar"></i> Installment payments</li>
                                            </ul>
                                        </div>
                            		</div>
                            	</div>
                                <div class="col-sm-5">
                                	<div class="store-image">
                                		<img src="assets/images/store-3.jpg" class="img-responsive" alt="">
                                        <div class="store-opening-hours">
                                        	<ul class="list-unstyled">
                                                <li><span>Mon</span> 8:00 - 20:00</li>
                                                <li><span>Tue</span> 8:00 - 20:00</li>
                                                <li><span>Wed</span> 12:00 - 20:00</li>
                                                <li><span>Thu</span> 12:00 - 20:00</li>
                                                <li><span>Fri, Sat, Sun</span> Closed</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- STORE - END -->
                            
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </section>
    <!-- ==========================
    	ESHOP - END 
    =========================== -->
    
    <!-- ==========================
    	NEWSLETTER - START 
    =========================== -->
    <section class="separator separator-newsletter">
    	<div class="container">
            <div class="newsletter-left">
                <div class="newsletter-badge">
                    <span>Subsribe & Get </span>
                    <span class="price">$15</span>
                    <span>discount</span>
                </div>
            </div>
            <div class="newsletter-right">
            	<div class="row">
                    <div class="col-sm-6">
                        <div class="newsletter-body">
                            <h3>Newsletter</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <form>
                            <div class="input-group input-group-lg">
                                <input type="email" class="form-control" placeholder="Enter email address">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button">Sign Up</button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ==========================
    	NEWSLETTER - END 
    =========================== -->
    
    <!-- ==========================
    	MODAL ADVERTISING  - START 
    =========================== -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modalAdvertising">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                    	<div class="col-sm-8">
                        	<h3>Dicount 10%</h3>
                        	<p>Enter your email address and get 10% discount for your first purchase.</p>
                            <form>
                                <div class="input-group">
                                    <input type="email" class="form-control" placeholder="Email Address">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="button">Submit</button>
                                    </span>
                                </div>
                            </form>
                            <div class="checkbox">  
                                <input id="modal-hide" type="checkbox" value="hidden">  
                                <label for="modal-hide">Don't show this popup again</label>
                            </div>
                        </div>
                        <div class="col-sm-4 hidden-xs">
                        	<img src="assets/images/lookbook-1.png" class="img-responsive" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<!-- ==========================
    	MODAL ADVERTISING - END 
    =========================== -->
    
    </div> <!-- PAGE - END -->

<?php }
}
?>