<?php
    include($_SERVER['DOCUMENT_ROOT'].'/sweeteaze/controllers/title.inc.php');
    require_once('controllers/config.inc.php');
    $currentPage = basename($_SERVER['SCRIPT_FILENAME']);

    ?>
<!DOCTYPE html>
<html>
<head>
    <!-- ==========================
    	Meta Tags 
    =========================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">     
        
    
        <!-- ==========================
            JS - START 
        =========================== -->
            <?php include('controllers/html_dependencies_top.inc.php'); ?>
        <!-- ==========================
            NEWSLETTER - END 
        =========================== --> 
    
</head>
<body>
	
    <!-- ==========================
    	SCROLL TOP - START 
    =========================== -->
    <div id="scrolltop" class="hidden-xs"><i class="fa fa-angle-up"></i></div>
    <!-- ==========================
    	SCROLL TOP - END 
    =========================== -->

    
    <div id="page-wrapper"> <!-- PAGE - START -->
    
	<!-- ==========================
    	HEADER - START 
    =========================== -->
        <?php include('controllers/header.inc.php'); ?>
    <!-- ==========================
    	HEADER - END 
    =========================== --> 
    
    <!-- ==========================
    	BREADCRUMB - START 
    =========================== -->
    <section class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <h2></h2>
                    <p></p>
                </div>
                <div class="col-xs-6">
                    <ol class="breadcrumb">
                        <li><a href="index.phtml">Home</a></li>
                        <li class="active">Terms & Conditions</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
	<!-- ==========================
    	BREADCRUMB - END 
    =========================== -->
    
    <!-- ==========================
    	ESHOP - START 
    =========================== -->
    <section class="content eshop">
        <div class="container">
        	<div class="row">
                <div class="col-sm-3 hidden-xs">
                    <aside class="sidebar">
                        
                        <!-- WIDGET:NAVIGATION - START -->
                        <div class="widget widget-navigation" id="scrollspy-nav">
                            <ul class="nav nav-pills nav-stacked affix-top" id="mynav" data-spy="affix" data-offset-top="165">
                                <li><a href="#headline-1" class="scroll">1 Lorem Ipsum</a></li>
                                <li><a href="#headline-2" class="scroll">2 Lorem Ipsum</a></li>
                                <li><a href="#headline-3" class="scroll">3 Lorem Ipsum</a></li>
                                <li><a href="#headline-4" class="scroll">4 Lorem Ipsum</a></li>
                                <li><a href="#headline-5" class="scroll">5 Lorem Ipsum</a></li>
                                <li><a href="#headline-6" class="scroll">6 Lorem Ipsum</a></li>
                            </ul>
                        </div>
                        <!-- WIDGET:NAVIGATION - END -->
                        
                    </aside>
                </div>
                
                <div class="col-sm-9">
                    <div class="default-style terms-conditions">
                        <h2 id="headline-1">1 Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.</p>
                        <p>Sed eget pulvinar quam, vel feugiat enim. Aliquam erat volutpat. Phasellus eu porta ipsum. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per. Vestibulum velmo.</p>
                        <h2 id="headline-2">2 Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.</p>
                        <p>Sed eget pulvinar quam, vel feugiat enim. Aliquam erat volutpat. Phasellus eu porta ipsum. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per. Vestibulum velmo.</p>
                        <h2 id="headline-3">3 Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.</p>
                        <p>Sed eget pulvinar quam, vel feugiat enim. Aliquam erat volutpat. Phasellus eu porta ipsum. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per. Vestibulum velmo.</p>
                        <h2 id="headline-4">4 Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.</p>
                        <p>Sed eget pulvinar quam, vel feugiat enim. Aliquam erat volutpat. Phasellus eu porta ipsum. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per. Vestibulum velmo.</p>
                        <h2 id="headline-5">5 Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.</p>
                        <p>Sed eget pulvinar quam, vel feugiat enim. Aliquam erat volutpat. Phasellus eu porta ipsum. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per. Vestibulum velmo.</p>
                        <h2 id="headline-6">6 Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per.</p>
                    	<p>Sed eget pulvinar quam, vel feugiat enim. Aliquam erat volutpat. Phasellus eu porta ipsum. Suspendisse aliquet imperdiet commodo. Aenean vel lacinia elit. Class aptent taciti sociosqu ad litora torquent per. Vestibulum velmo.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ==========================
    	ESHOP - END 
    =========================== -->
       
    <!-- ==========================
    	NEWSLETTER - START 
    =========================== -->
   <?php include('controllers/newsletter.inc.php') ?>
    <!-- ==========================
    	NEWSLETTER - END 
    =========================== -->
    
    <!-- ==========================
    	FOOTER - START 
    =========================== -->

     <?php include('controllers/footer.inc.php'); ?>

    <!-- ==========================
    	FOOTER - END 
    =========================== -->

    
    </div> <!-- PAGE - END -->       
        
    
        <!-- ==========================
            JS - START 
        =========================== -->
            <?php include('controllers/html_dependencies_bottom.inc.php'); ?>
        <!-- ==========================
            NEWSLETTER - END 
        =========================== --> 
</body>
</html>